### ISSUE TITLE
Importing pip dependencies dependencies

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/rules_python#110]
I am importing `pytest` to use a some of it's helper methods in my tests, however I get it saying module `py` doesn't exist.

Does the generated `requirement` return all module paths for the module and it's own dependency modules?

Error returned:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //cosmic:brokers_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bweston/.cache/bazel/_bazel_bweston/de01b7b9e438d87e08f8fe10543c143f/sandbox/linux-sandbox/1/execroot/[radecated]]/bazel-out/k8-fastbuild/bin/cosmic/brokers_test.runfiles/[radecated]]/cosmic/brokers_test.py", line 2, in <module>
    import pytest
  File "/home/bweston/.cache/bazel/_bazel_bweston/de01b7b9e438d87e08f8fe10543c143f/sandbox/linux-sandbox/1/execroot/[radecated]]/bazel-out/k8-fastbuild/bin/cosmic/brokers_test.runfiles/pypi__pytest_3_6_0/pytest.py", line 9, in <module>
    from _pytest.config import (
  File "/home/bweston/.cache/bazel/_bazel_bweston/de01b7b9e438d87e08f8fe10543c143f/sandbox/linux-sandbox/1/execroot/[radecated]]/bazel-out/k8-fastbuild/bin/cosmic/brokers_test.runfiles/pypi__pytest_3_6_0/_pytest/config.py", line 10, in <module>
    import py
ImportError: No module named py
```

Here is my workspace:
```
workspace(name = '[radecated]')

git_repository(
    name = 'io_bazel_rules_python',
    remote = 'https://github.com/bazelbuild/rules_python.git',
    commit = '8b5d0683a7d878b28fffe464779c8a53659fc645',
)

load('@io_bazel_rules_python//python:pip.bzl', 'pip_repositories', 'pip_import')

pip_repositories()

pip_import(
    name = 'third_party_deps',
    requirements = '//:requirements.txt',
)

load('@third_party_deps//:requirements.bzl', 'pip_install')
pip_install()
```

Here is my BUILD file
```
package(default_visibility = ["//visibility:public"])

load(
  '@io_bazel_rules_python//python:python.bzl',
  'py_library', 'py_test',
)

load('@third_party_deps//:requirements.bzl', 'requirement')

py_library(
    name = 'cosmic',
    srcs = [
        '__init__.py',
        'brokers.py',
    ],
)

py_library(
    name = 'external',
    deps = [
        requirement('requests'),
        requirement('responses'),
        requirement('pytest'),
    ],
)

py_test(
    name = 'brokers_test',
    srcs = [
        'brokers_test.py',
    ],
    deps = [
        ':cosmic',
        ':external',
    ],
)
```

**Comment by bweston92** [comment]
If I add `requirement('py'),` to the `deps` list is works (or at least moves on to the next dependency that is missing in this case `attr`) by `attr` it self cannot be found.

So doing
```
py_library(
    name = 'external',
    deps = [
        requirement('requests'),
        requirement('responses'),
        requirement('pytest'),
        requirement('py'),
    ],
)
```

Gives:
```
```

And doing:
```
py_library(
    name = 'external',
    deps = [
        requirement('requests'),
        requirement('responses'),
        requirement('pytest'),
        requirement('py'),
        requirement('attr'),
    ],
)
```

Gives:
```
Could not find pip-provided dependency: 'attr'
```

**Comment by benley** [comment]
Possibly related: https://github.com/bazelbuild/rules_python/pull/90, https://github.com/bazelbuild/rules_python/issues/70
