### ISSUE TITLE
Unittest failures use absolute paths inside the Bazel sandbox, breaking IDE/editor support

### ISSUE THREAD

**Issue by nikhilm** [bazelbuild/rules_python#1144]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `py_test`.

### Is this a regression?

I don't think so.

### Description

When `bazel test`ing a `unittest` test, file paths in stack traces are absolute, and refer to files in the sandbox. Several editors (including Jetbrains IDE integration) will recognize paths in program executions and allow you to quickly jump to the failing test. This ease of use is broken due to the issue.

It would be nice if this could be fixed in the test runner. Alternatively, what are options IDE implementors could tack on top to handle this?

## 🔬 Minimal Reproduction

1. Clone https://github.com/nikhilm/bazel-python-example, which is a simple test case.
2. Run `python3 example_test.py` which is a non-Bazel execution. See how the paths are directly to the file, so the editor can jump to the failing case.
```
F
======================================================================
FAIL: test_basic (__main__.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nikhil/bazel-python-example/example_test.py", line 5, in test_basic
    assert False
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```
4. Run `bazel test :example_test --test_output=all`
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:example_test
-----------------------------------------------------------------------------
F
======================================================================
FAIL: test_basic (__main__.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nikhil/.cache/bazel/_bazel_nikhil/1387d3b43bc2d9fe375efe6fbda723d7/sandbox/linux-sandbox/15/execroot/__main__/bazel-out/k8-fastbuild/bin/example_test.runfiles/__main__/example_test.py", line 5, in test_basic
    assert False
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

Notice how the path is in the sandbox execroot that no longer exists? Obviously bazel vs non-bazel is not a fair comparison, but the bazel support for other languages (like Java) _does_ offer output that IDEs can jump to. For example, here is a Java test failure

```
expected: NOTE
but was : ERROR

	at com.google.idea.blaze.python.issueparser.PyIssueParserProviderTest.testParsePyTypeError(PyIssueParserProviderTest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

And here is how that appears when run under Intellij Bazel, with the file clickable and taking me to the failing line.

![image](https://user-images.githubusercontent.com/78682/229304664-2656354d-a424-46fb-a113-0c1d645d19e1.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux (Ubuntu 22.10)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.16.0
Build label: 6.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Mar 15 15:44:56 2023 (1678895096)
Build timestamp: 1678895096
Build timestamp as int: 1678895096

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.20.0
  </code>
</pre>

**Comment by nikhilm** [comment]
So upon further experimentation, Intellij Bazel can actually resolve these paths to workspace files when running a binary/test in the **Debug** configuration, but not the **Run** configuration.
