### ISSUE TITLE
gazelle not working with windows

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#1163]
# 🐞 bug report

### Affected Rule

Gazelle is not finding the default Python interpreter when configuring gazelle with bzlmod.

### Is this a regression?

No.

### Description

When generating the modules_map for gazelle, the rules are not finding Python in its default path.

```
ERROR: An error occurred during the fetch of repository 'rules_python~override~pip~pip_typing_extensions':
   Traceback (most recent call last):
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 658, column 53, in _whl_library_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 80, column 17, in _resolve_python_interpreter
                fail("python interpreter `{}` not found in PATH".format(python_interpreter))
Error in fail: python interpreter `python.exe` not found in PATH
```

## 🔬 Minimal Reproduction

See https://github.com/bazelbuild/rules_python/pull/1155

## 🔥 Exception or Error

Run:

```
bazelisk.exe build //:modules_map
```

Part of the error will end with:

```
ERROR: An error occurred during the fetch of repository 'rules_python~override~pip~pip_typing_extensions':
   Traceback (most recent call last):
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 658, column 53, in _whl_library_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 80, column 17, in _resolve_python_interpreter
                fail("python interpreter `{}` not found in PATH".format(python_interpreter))
Error in fail: python interpreter `python.exe` not found in PATH
ERROR: <builtin>: fetching whl_library rule @rules_python~override//python:rules_python~override~pip~pip_typing_extensions: Traceback (most recent call last):
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 658, column 53, in _whl_library_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 80, column 17, in _resolve_python_interpreter
                fail("python interpreter `{}` not found in PATH".format(python_interpreter))
Error in fail: python interpreter `python.exe` not found in PATH
ERROR: C:/users/chris/_bazel_chris/r4du22do/external/rules_python~override~pip~pip/typing_extensions/BUILD.bazel:13:6: @rules_python~override~pip~pip//typing_extensions:whl depends on @rules_python~override~pip~pip_typing_extensions//:whl in repository @rules_python~override~pip~pip_typing_extensions which failed to fetch. no such package '@rules_python~override~pip~pip_typing_extensions//': python interpreter `python.exe` not found in PATH
ERROR: Analysis of target '//:modules_map' failed; build aborted:
INFO: Elapsed time: 0.133s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 5 targets configured)
```

## 🌍  Your Environment

**Operating System:**

Windows 10

C:\Users\chris\Workspace\rules_python\examples\bzlmod>bazelisk version
Bazelisk version: v1.15.0
Build label: 6.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:54:13 2022 (1671465253)
Build timestamp: 1671465253
Build timestamp as int: 1671465253

**Rules_python version:**

main

**Anything else relevant?**

**Comment by chrislovecnm** [comment]
Well

```
bazelisk --output_user_root=C:/b build --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimental_repository_cache_hardlinks --disk_cache=
```

Does build, but the test is failing.

```
C:\Users\chris\Workspace\rules_python\examples\bzlmod>bazelisk --output_user_root=C:/b build --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimental_repository_cache_hardlinks --disk_cache=
(15:47:06) INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
(15:47:06) INFO: Reading rc options for 'build' from c:\users\chris\workspace\rules_python\examples\bzlmod\.bazelrc:
  Inherited 'common' options: --experimental_enable_bzlmod
(15:47:06) INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/chris/AppData/Local/Microsoft/WindowsApps/python.exe
(15:47:06) WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
(15:47:06) INFO: Current date is 2023-04-11
(15:47:06) INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
(15:47:06) INFO: Found 0 targets...
(15:47:06) INFO: Elapsed time: 0.562s, Critical Path: 0.01s
(15:47:06) INFO: 1 process: 1 internal.
(15:47:06) INFO: Build completed successfully, 1 total action

C:\Users\chris\Workspace\rules_python\examples\bzlmod>bazelisk --output_user_root=C:/b run --show_progress_rate_limit=5
--curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimen
tal_repository_cache_hardlinks --disk_cache= //:gazelle_python_manifest.update
(15:47:49) INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
(15:47:49) INFO: Reading rc options for 'run' from c:\users\chris\workspace\rules_python\examples\bzlmod\.bazelrc:
  Inherited 'common' options: --experimental_enable_bzlmod
(15:47:49) INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/chris/AppData/Local/Microsoft/WindowsApps/python.exe
(15:47:49) INFO: Current date is 2023-04-11
(15:47:49) INFO: Repository rules_python~override~pip~pip_idna instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_platformdirs instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_certifi instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_dill instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_pylint instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_yamllint instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_pyyaml instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_python_dateutil instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_chardet instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_requests instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_pathspec instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_astroid instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_mccabe instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_s3cmd instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_python_magic instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_lazy_object_proxy instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_isort instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_setuptools instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_tomlkit instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) INFO: Repository rules_python~override~pip~pip_six instantiated at:
  callstack not available
Repository rule whl_library defined at:
  C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
(15:47:49) ERROR: An error occurred during the fetch of repository 'rules_python~override~pip~pip_idna':
   Traceback (most recent call last):
        File "C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 658, column 53, in _whl_library_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 80, column 17, in _resolve_python_interpreter
                fail("python interpreter `{}` not found in PATH".format(python_interpreter))
Error in fail: python interpreter `python.exe` not found in PATH
(15:47:49) ERROR: <builtin>: fetching whl_library rule @rules_python~override//python:rules_python~override~pip~pip_idna: Traceback (most recent call last):
        File "C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 658, column 53, in _whl_library_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/b/r4du22do/external/rules_python~override/python/pip_install/pip_repository.bzl", line 80, column 17, in _resolve_python_interpreter
                fail("python interpreter `{}` not found in PATH".format(python_interpreter))
Error in fail: python interpreter `python.exe` not found in PATH
(15:47:49) ERROR: C:/b/r4du22do/external/rules_python~override~pip~pip/idna/BUILD.bazel:13:6: @rules_python~override~pip~pip//idna:whl depends on @rules_python~override~pip~pip_idna//:whl in repository @rules_python~override~pip~pip_idna which failed to fetch. no such package '@rules_python~override~pip~pip_idna//': python interpreter `python.exe` not found in PATH
(15:47:49) ERROR: Analysis of target '//:gazelle_python_manifest.update' failed; build aborted:
(15:47:49) INFO: Elapsed time: 0.451s
(15:47:49) INFO: 0 processes.
(15:47:49) FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
(15:47:49) ERROR: Build failed. Not running target
```

Build finds python, but the pip rules do not.

**Comment by chrislovecnm** [comment]
This is because bazel in windows has enable runfiles disabled by default. Turn it in and voila. Add it to your .bazelrc
