### ISSUE TITLE
rules_python is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1185]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2984#0187c5a7-8c82-4bf4-8edc-bc61496edab0

Platform : macOS 

Logs:
```
ERROR: /Users/buildkite/builds/bk-imacpro-8/bazel-downstream-projects/rules_python/tools/build_defs/python/tests/py_test/BUILD.bazel:18:19: in test_non_mac_doesnt_require_darwin_for_execution_test rule //tools/build_defs/python/tests/py_test:test_non_mac_doesnt_require_darwin_for_execution:
--
  | Traceback (most recent call last):
  | File "/private/var/tmp/_bazel_buildkite/423e4bd8d06d193ec99dc7a74423eafe/external/rules_testing/lib/analysis_test.bzl", line 200, column 13, in wrapped_impl
  | impl(env, target)
  | File "/Users/buildkite/builds/bk-imacpro-8/bazel-downstream-projects/rules_python/tools/build_defs/python/tests/py_test/py_test_tests.bzl", line 89, column 28, in _test_non_mac_doesnt_require_darwin_for_execution_impl
  | ).requirements().keys().not_contains("requires-darwin")
  | Error: 'struct' value has no field or method 'not_contains'
  | Available attributes: actual, contains, contains_at_least, contains_at_least_predicates, contains_exactly, contains_exactly_predicates, contains_none_of, contains_predicate, has_size, not_contains_predicate
  | (04:20:02) ERROR: /Users/buildkite/builds/bk-imacpro-8/bazel-downstream-projects/rules_python/tools/build_defs/python/tests/py_test/BUILD.bazel:18:19: Analysis of target '//tools/build_defs/python/tests/py_test:test_non_mac_doesnt_require_darwin_for_execution' failed

```
Reference : https://github.com/bazelbuild/bazel/issues/18170
Unable to reproduce in local setup.

CC @meteorcloudy, @rickeylev

**Comment by rickeylev** [comment]
Reproducing this requires the host to be a mac.

What's happening is...
* The test expects the target-under-test to be configured for not-mac, but isn't forcing it to be not-mac.
* When a linux host builds, the TUT is not mac, so it passes.
* When a mac host builds, the TUT is mac, so it fails.

The error is a bit confusing because it also reveals a bug in rules_testing -- the missing not_contains method. That code path is only being taken, though, because the test is seeing the unexpected value, so it tries to assert on its contents.

https://github.com/bazelbuild/rules_python/pull/1183 is out to fix.

**Comment by meteorcloudy** [comment]
A bisect points to https://github.com/bazelbuild/bazel/commit/18955851947002ea39854b5d2aa3e6fa81ef8bf3

BTW, I'm adding bisect feature to Bazelisk, which should help identifying Bazel breaking changes much easier: https://github.com/bazelbuild/bazelisk/pull/451

**Comment by rickeylev** [comment]
My guess as to why enabling the Starlark impl caused this is the Starlark impl uses platforms, while the Java one uses the --cpu string.

Since platforms are the intended way to identify the platform over --cpu, I'll document this as a behavior change in https://github.com/bazelbuild/bazel/issues/15897
