### ISSUE TITLE
asyncpg fails to import under bzlmod, works under workspace

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/rules_python#1222]
# 🐞 bug report

### Affected Rule

No single rule, combination of pip.parse and py_binary under bzlmod

### Is this a regression?

Somewhat, works under WORKSPACE but not under bzlmod. Also tested on a couple of older versions of rules_python, with same error

### Description

Attempting to import asyncpg under bzlmod fails with `ModuleNotFoundError` when it attempts to import a cython module .so. Using the exact same requirements lock file and src files under WORKSPACE, there is no error.

Looking at the generated runfiles, the required .so appears to be present but I haven't dug any deeper to check for differences in path etc.

## 🔬 Minimal Reproduction

Use repo here: https://github.com/aaliddell/rules_python_bzlmod_asyncpg_demo

Run with `bazel run //:test` and you will get no error
Run with `bazel run --enable_bzlmod //:test` and you should get error

## 🔥 Exception or Error

```
Traceback (most recent call last):
  File "<snip>/_main/app/src/main.py", line 2, in <module>
    import asyncpg
  File "<snip>/rules_python~0.21.0~pip~pip_deps_asyncpg/site-packages/asyncpg/__init__.py", line 8, in <module>
    from .connection import connect, Connection  # NOQA
  File "<snip>/rules_python~0.21.0~pip~pip_deps_asyncpg/site-packages/asyncpg/connection.py", line 23, in <module>
    from . import connect_utils
  File "<snip>/rules_python~0.21.0~pip~pip_deps_asyncpg/site-packages/asyncpg/connect_utils.py", line 30, in <module>
    from . import protocol
  File "<snip>/rules_python~0.21.0~pip~pip_deps_asyncpg/site-packages/asyncpg/protocol/__init__.py", line 9, in <module>
    from .protocol import Protocol, Record, NO_TIMEOUT, BUILTIN_TYPE_NAME_MAP
ModuleNotFoundError: No module named 'asyncpg.protocol.protocol'
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Fedora 38
Linux 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.16.0
Build label: 6.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Mar 15 15:44:56 2023 (1678895096)
Build timestamp: 1678895096
Build timestamp as int: 1678895096
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.21.0
  </code>
</pre>

**Anything else relevant?**

**Comment by aaliddell** [comment]
Ok, I see the problem. Under bzlmod I don't have `python_interpreter_target` so the wrong version of asyncpg is being downloaded for the target toolchain (3.10 vs 3.11). Seems like I need to wait for #1155 to be in a release for a simple solution. I would also suggest the demo code in the readme gets updated to use the correct python for pip.parse.
