### ISSUE TITLE
CI Flake Mac OpenJDK

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#1224]
I have seen the following flake multiple times with the Mac builds.

See: https://buildkite.com/bazel/rules-python-python/builds/4826#01881ff9-bfb9-491f-a410-5ffaef79888a

```log
(17:16:58) INFO: Reading rc options for 'build' from /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/.bazelrc:
--
  | 'build' options: --enable_runfiles
  | (17:16:59) DEBUG: gazelle@0.27.0/MODULE.bazel:7:6: WARNING: The bazel_gazelle Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
  | (17:16:59) DEBUG: rules_go@0.37.0/MODULE.bazel:8:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
  | (17:16:59) DEBUG: rules_go@0.33.0/MODULE.bazel:7:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
  | (17:17:01) WARNING: Option 'remote_default_platform_properties' is deprecated: --remote_default_platform_properties has been deprecated in favor of --remote_default_exec_properties.
  | (17:17:01) INFO: Current date is 2023-05-15
  | (17:17:04) DEBUG: Rule 'rules_python~override~python~python3_x86_64-apple-darwin' indicated that a canonical reproducible form can be obtained by modifying arguments url = ["https://github.com/indygreg/python-build-standalone/releases/download/20230116/cpython-3.9.16+20230116-x86_64-apple-darwin-install_only.tar.gz"] and dropping ["urls"]
  | (17:17:04) DEBUG: Repository rules_python~override~python~python3_x86_64-apple-darwin instantiated at:
  | callstack not available
  | Repository rule python_repository defined at:
  | /private/var/tmp/_bazel_buildkite/7599fdbf5f3ac86c93cc4250b368bd74/external/rules_python~override/python/repositories.bzl:366:36: in <toplevel>
  | (17:17:35) INFO: Analyzed 10 targets (171 packages loaded, 15909 targets configured).
  | (17:17:35) INFO: Found 10 targets...
  | (17:17:35) WARNING: cleared convenience symlink(s) bazel-bin, bazel-testlogs because their destinations would be ambiguous
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements_Utest-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4317360176'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements_Utest-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4358975536'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements.update-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4317360176'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements_Utest-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4559855664'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements.update-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4358975536'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements.update-runfiles failed: missing input file '@rules_python~override~internal_deps~pypi__pip//:pip/_vendor/pyparsing/__pycache__/core.cpython-39.pyc.4559855664'
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements.update-runfiles failed: 3 input file(s) do not exist
  | (17:17:37) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25: Middleman _middlemen/requirements_Utest-runfiles failed: 3 input file(s) do not exist
  | (17:17:38) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/rules-python-python/examples/bzlmod_build_file_generation/BUILD.bazel:19:25 Middleman _middlemen/requirements_Utest-runfiles failed: 3 input file(s) do not exist
  | (17:17:38) INFO: Elapsed time: 39.941s, Critical Path: 2.17s
  | (17:17:38) INFO: 60 processes: 19 remote cache hit, 41 internal.
  | (17:17:38) FAILED: Build did NOT complete successfully
  | bazel build failed with exit code 1
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1
```

I have seen this before as well:

```
May 04 17:16:00.138 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
--
  | May 04 17:16:00.138 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
  | May 04 17:16:00.138 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
  | May 04 17:16:00.138 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
  | May 04 17:16:00.138 ERROR bazelci_agent::artifact::upload: The system cannot find the file specified. (os error 2)
  | Error: The system cannot find the file specified. (os error 2)
  | Exception in thread Thread-1:
  | Traceback (most recent call last):
  | File "C:\python3\lib\threading.py", line 973, in _bootstrap_inner
  | self.run()
  | File "C:\python3\lib\threading.py", line 910, in run
  | self._target(*self._args, **self._kwargs)
  | File "c:\b\bk-windows-bt5g\bazel\rules-python-python\bazelci.py", line 2424, in upload_test_logs_from_bep
  | execute_command(
  | File "c:\b\bk-windows-bt5g\bazel\rules-python-python\bazelci.py", line 2474, in execute_command
  | return subprocess.run(
  | File "C:\python3\lib\subprocess.py", line 528, in run
  | raise CalledProcessError(retcode, process.args,
  | subprocess.CalledProcessError: Command '['C:\\temp\\tmpikfc45yc\\bazelci-agent.exe', 'artifact', 'upload', '--delay=5', '--mode=buildkite', '--build_event_json_file=C:\\temp\\tmpikfc45yc\\test_bep.json']' returned non-zero exit status 1.
  | 2023/05/04 17:16:04 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": net/http: TLS handshake timeout
```

**Comment by chrislovecnm** [comment]
@rickeylev can I file an issue with the test group, or do you need to file it internally?

**Comment by chrislovecnm** [comment]
Fixed
