### ISSUE TITLE
rules Python bzlmod integration tests and examples are failing with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1299]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3149#01892e1b-ed7d-40e0-9834-e7d7ac63ea83

Platform: MacOs, Ubuntu, Windows

Logs : 
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NullPointerException: Cannot invoke "com.google.devtools.build.lib.bazel.bzlmod.BazelModuleResolutionEvent.getExtensionUsagesById()" because "this.moduleResolutionEvent" is null
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileModule.combineModuleExtensions(BazelLockFileModule.java:111)
	at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileModule.afterCommand(BazelLockFileModule.java:88)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:627)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:674)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:245)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
        bazel coverage failed with exit code 37
        Error: The command exited with status 1
```

CC Greenteam  @Wyverald

**Comment by rickeylev** [comment]
I wasn't able to repro the crash this with the instructions above.

`bazel test` is OK.

`bazel coverage` has a couple failures, but not a crash. I haven't looked into what the cause is.

The CI link shows test is ok, but coverage had the crash.

**Comment by Wyverald** [comment]
@SalmaSamy has a pending fix for this at HEAD.

**Comment by sgowroji** [comment]
Also seeing below errors for  https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3155#01893d8e-ea2e-4a6a-9b42-623bdab05f5f CI .

Logs :  
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-28rd/bazel-downstream-projects/rules_python/python/cc/BUILD.bazel:14:22: in current_py_cc_headers rule //python/cc:current_py_cc_headers: non-test target '//python/cc:current_py_cc_headers' depends on testonly target '//tests/cc:fake_py_cc_toolchain_impl' and doesn't have testonly attribute set
(02:22:54) ERROR: /var/lib/buildkite-agent/builds/bk-docker-28rd/bazel-downstream-projects/rules_python/python/cc/BUILD.bazel:14:22: Analysis of target '//python/cc:current_py_cc_headers' failed
```

Steps :
```
git clone -v https://github.com/bazelbuild/rules_python.git
git reset b8f16458c1d785a24921e569cc6174e8e3f6b45e --hard
export USE_BAZEL_VERSION=7845acae9769a72dc507dc2f57c4e032ebf429d3
bazel build ... @rules_python//examples/wheel/...
```
Culprit : https://github.com/bazelbuild/bazel/commit/18aeb52a59e65efcbeac7041faf60d81f9d434cb

**Comment by SalmaSamy** [comment]
@sgowroji the fix for null pointer issue is submitted.

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by sgowroji** [comment]
Yes @chrislovecnm We can close the above issue and for this https://github.com/bazelbuild/rules_python/issues/1299#issuecomment-1628505662 i have referenced another new issue https://github.com/bazelbuild/rules_python/issues/1324
