### ISSUE TITLE
bzlmod/ pip: Initial lock file creation and empty lock file

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#1343]
When you remove the lock file:

`rm rules_python/examples/bzlmod/requirements_lock_3_9.txt`

You cannot run `bazel run :requirements_3_9.update`

```
$ bazel run :requirements_3_9.update
ERROR: Traceback (most recent call last):
        File "/home/clove/.cache/bazel/_bazel_clove/4d81ba2c4676ec44765d3282b1133dda/external/rules_python~override/python/extensions/pip.bzl", line 295, column 48, in _pip_impl
                _create_versioned_pip_and_whl_repos(module_ctx, pip_attr, hub_whl_map)
        File "/home/clove/.cache/bazel/_bazel_clove/4d81ba2c4676ec44765d3282b1133dda/external/rules_python~override/python/extensions/pip.bzl", line 109, column 48, in _create_versioned_pip_and_whl_repos
                requirements_lock_content = module_ctx.read(requrements_lock)
Error in read: Not a regular file: /home/clove/Workspace/src/github.com/bazelbuild/rules_python/examples/bzlmod/requirements_lock_3_9.txt
ERROR: error evaluating module extension pip in @rules_python~override//python/extensions:pip.bzl
INFO: Elapsed time: 0.094s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
ERROR: Build failed. Not running target
```

When you create an empty lock file:

```
$ cp /dev/null requirements_lock_3_9.txt

```

You get the following error:

```
# clove @ DESKTOP-BRJVH3P in ~/Workspace/src/github.com/bazelbuild/rules_python/examples/bzlmod on git:update-deps x [12:42:16]
$ bazel run :requirements_3_9.update
ERROR: Traceback (most recent call last):
        File "/home/clove/.cache/bazel/_bazel_clove/4d81ba2c4676ec44765d3282b1133dda/external/rules_python~override/python/extensions/pip.bzl", line 300, column 21, in _pip_impl
                fail((
Error in fail: Default python version '3.9' missing in pip hub 'pip': update your pip.parse() calls so that includes `python_version = "3.9"`
ERROR: error evaluating module extension pip in @rules_python~override//python/extensions:pip.bzl
INFO: Elapsed time: 0.129s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
ERROR: Build failed. Not running target
```

@rickeylev, I think you have a fix for the empty file, but the missing file is still an issue.

**Comment by rickeylev** [comment]
> I think you have a fix for the empty file, but the missing file is still an issue.

Eh? I don't have any fix for an empty file. I have a fix so that pip.parse doesn't require pip hubs to be configured for the default python version.

I don't think this is specific to bzlmod? I think a missing requirements file also gives some error about the file missing with workspace. From what I remember, the basic issue is the lock file is specified as an input to the update target. When it isn't present, then Starlark gives an error about the input missing. Using `glob()` would work around this (it's ok with files missing).

**Comment by groodt** [comment]
The error message seems clear to me. Is this a docs issue? 

It would be strange to me to create a repository rule just to create an empty file. How else would you get around this otherwise?
