### ISSUE TITLE
metadata-generation-failed on dependency (cugraph)

### ISSUE THREAD

**Issue by fferroni** [bazelbuild/rules_python#1355]
# 🐞 bug report

### Description

Using pip install with python3.10, installing cugraph works fine.
Using 3.10 interpreter and trying to install the same package `cugraph` with `rules_python` doesn't work.
I am getting a `metadata-generation-failed` error.

## 🔬 Minimal Reproduction

`WORKSPACE`
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.24.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.24.0/rules_python-0.24.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python3_10",
    python_version = "3.10",
)

load("@python3_10//:defs.bzl", "interpreter")

# Create a central external repo that contains Bazel targets for all the
# third-party packages specified in the requirements.bazel.txt file.
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pypi",
    python_interpreter_target = interpreter,
    quiet = False,
    requirements_lock = "//third_party/pip:requirements.txt",
)

load("@pypi//:requirements.bzl", "install_deps")

# Initialize repositories for all packages in requirements.txt.
install_deps()
```

`third_party/pip/BUILD`
```
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.

load("@rules_python//python:pip.bzl", "compile_pip_requirements")

package(default_visibility = ["//visibility:public"])

# This rule adds a convenient way to update the requirements file
# bazel run //third_party/pip:requirements.update
compile_pip_requirements(
    name = "requirements",
    timeout = "long",
    requirements_in = "requirements.in",
    requirements_txt = "requirements.txt",
)
```

`requirements.in`
```
--extra-index-url=https://pypi.ngc.nvidia.com
cugraph-cu11==23.6.2
```
The `requirements.txt` is generated using `bazel run //third_party/pip:requirements.update` and is created without problem.

## 🔥 Exception or Error

`bazel build @pypi_cugraph_cu11//...`
gives
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cugraph-cu11==23.6.2
  Using cached cugraph-cu11-23.6.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-jiige1e3/cugraph-cu11_100b74a40ee349dcb093540f73ead043/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 455, in <module>
    main()
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 432, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--extra-index-url', 'https://pypi.ngc.nvidia.com', '-r', '/tmp/tmpce498m_j']' returned non-zero exit status 1.
INFO: Repository pypi_cugraph_cu11 instantiated at:
  /home/francesco/dev/cvfactory/WORKSPACE:47:13: in <toplevel>
  /home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/pypi/requirements.bzl:49:20: in install_deps
Repository rule whl_library defined at:
  /home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/pip_repository.bzl:715:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pypi_cugraph_cu11':
   Traceback (most recent call last):
        File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/pip_repository.bzl", line 691, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library pypi_cugraph_cu11 failed: Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cugraph-cu11==23.6.2
  Using cached cugraph-cu11-23.6.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
 (  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-jiige1e3/cugraph-cu11_100b74a40ee349dcb093540f73ead043/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 455, in <module>
    main()
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 432, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--extra-index-url', 'https://pypi.ngc.nvidia.com', '-r', '/tmp/tmpce498m_j']' returned non-zero exit status 1.
) error code: '1'
ERROR: /home/francesco/dev/cvfactory/WORKSPACE:47:13: fetching whl_library rule //external:pypi_cugraph_cu11: Traceback (most recent call last):
        File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/pip_repository.bzl", line 691, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library pypi_cugraph_cu11 failed: Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cugraph-cu11==23.6.2
  Using cached cugraph-cu11-23.6.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
 (  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-jiige1e3/cugraph-cu11_100b74a40ee349dcb093540f73ead043/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 455, in <module>
    main()
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 432, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--extra-index-url', 'https://pypi.ngc.nvidia.com', '-r', '/tmp/tmpce498m_j']' returned non-zero exit status 1.
) error code: '1'
ERROR: whl_library pypi_cugraph_cu11 failed: Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting cugraph-cu11==23.6.2
  Using cached cugraph-cu11-23.6.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
 (  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-jiige1e3/cugraph-cu11_100b74a40ee349dcb093540f73ead043/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 455, in <module>
    main()
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 432, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--extra-index-url', 'https://pypi.ngc.nvidia.com', '-r', '/tmp/tmpce498m_j']' returned non-zero exit status 1.
) error code: '1'
INFO: Elapsed time: 2.880s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

## 🌍  Your Environment

**Operating System:**
Ubuntu 22.04

**Output of `bazel version`:**
```
Bazelisk version: v1.16.0
Build label: 5.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:25 2022 (1671120865)
Build timestamp: 1671120865
Build timestamp as int: 1671120865
```

**Rules_python version:**
`0.24`

**Anything else relevant?**

Using normal pip things work fine

```
conda create -n test_py310 python=3.10
conda activate test_py310
pip install cudf-cu11 cugraph-cu11 --extra-index-url=https://pypi.nvidia.com
```
Link to RAPIDS installation [matrix](https://docs.rapids.ai/install?_gl=1*13c1621*_ga*MTA2MjIyNzk4OS4xNjg5NjA3ODg1*_ga_RKXFW6CM42*MTY5MDk3MDc3MC43LjAuMTY5MDk3MDc3MC42MC4wLjA.)

**Comment by rlratzel** [comment]
Are you able to share the `setup.py` file being used that's mentioned in the traceback?
```
        File "/tmp/pip-wheel-jiige1e3/cugraph-cu11_100b74a40ee349dcb093540f73ead043/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
```
I'm not familiar with bazel, but since a `pip install` call to cugraph ouside of bazel works, I'm assuming that the setup.py file here is incorrect and/or the version of setuptools being used isn't compatible?

**Comment by bdice** [comment]
Please try `--extra-index-url=https://pypi.nvidia.com` instead of `--extra-index-url=https://pypi.ngc.nvidia.com` in your `requirements.in` file. This server has moved.

See also: https://docs.rapids.ai/install#pip-issues

**Comment by fferroni** [comment]
Seems like I get the same issue unfortunately.

```
Traceback (most recent call last):
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 455, in <module>
    main()
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 432, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/python3_10_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--extra-index-url', 'https://pypi.nvidia.com', '-r', '/tmp/tmp2x_s4pot']' returned non-zero exit status 1.
) error code: '1'
ERROR: /home/francesco/dev/cvfactory/WORKSPACE:47:13: fetching whl_library rule //external:pypi_cugraph_cu11: Traceback (most recent call last):
        File "/home/francesco/.cache/bazel/_bazel_francesco/daf4963c8d6dc6fece0d79b9d3209651/external/rules_python/python/pip_install/pip_repository.bzl", line 691, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library pypi_cugraph_cu11 failed: Looking in indexes: https://pypi.org/simple,
https://pypi.nvidia.com
Collecting cugraph-cu11==23.6.2
  Downloading https://urm.nvidia.com/artifactory/api/pypi/nv-shared-pypi/packages/packages/e7/4d/a53e006fad8068423d781a0e33703253ca9e2ff9713e6261f68df6ca14b7/cugraph-cu11-23.6.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
 (  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-6uyxkska/cugraph-cu11_a774983093714dc4bf12e9834f5cb23d/setup.py", line 81, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
```
