### ISSUE TITLE
Error " no such package '@docs_deps_babel//': whl_library docs_deps_babel failed" with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1530]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3428#018b88a0-8708-4bd5-ad7b-69baa871d4f7

Platform :  Multiple

Logs:
```
ERROR: no such package '@docs_deps_babel//': whl_library docs_deps_babel failed: Collecting babel==2.12.1 (from -r /tmp/tmpid1jb1s6 (line 1))
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
                                              0.0/10.1 MB 742.0 kB/s eta 0:00:14
 (ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    babel==2.12.1 from https://files.pythonhosted.org/packages/df/c4/1088865e0246d7ecf56d819a233ab2b72f7d6ab043965ef327d0731b5434/Babel-2.12.1-py3-none-any.whl (from -r /tmp/tmpid1jb1s6 (line 1)):
        Expected sha256 b4246fb7677d3b98f501a39d43396d3cafdc8eadb045f4a31be01863f655c610
        Expected     or cc2d99999cd01d44420ae725a21c9e3711b3aadc7976d6147f622d8581963455
             Got        9aebf7fab2060a111cd0b2757c0de20316b41dd0235ce5d6a2ce994cf43e6e4e
 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/lib/buildkite-agent/builds/bk-docker-ft6b/bazel-downstream-projects/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 207, in <module>
    main()
  File "/var/lib/buildkite-agent/builds/bk-docker-ft6b/bazel-downstream-projects/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 192, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/c2424c3924a05e9cdbea7e5a3704ee76/external/python_3_11_6_x86_64-unknown-linux-gnu/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/c2424c3924a05e9cdbea7e5a3704ee76/external/python_3_11_6_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '-r', '/tmp/tmpid1jb1s6']' returned non-zero exit status 1.
) error code: '1'
(02:20:47) INFO: ToolchainResolution: Target platform @buildkite_config//config:platform: Selected execution platform @buildkite_config//config:platform,
(02:20:47) INFO: ToolchainResolution: Performing resolution of @bazel_tools//tools/jdk:toolchain_type for target platform @buildkite_config//config:platform
      ToolchainResolution:   Rejected toolchain @rules_java_builtin//toolchains:toolchain_java10; mismatching config settings: toolchain_java10_version_setting
      ToolchainResolution:   Rejected toolchain @rules_java_builtin//toolchains:toolchain_java11; mismatching config settings: toolchain_java11_version_setting
      ToolchainResolution:   Toolchain @rules_java_builtin//toolchains:toolchain_java8 is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Compatible execution platform @buildkite_config//config:platform
      ToolchainResolution:     Skipping execution platform @buildkite_config//config:platform; it has already selected a toolchain
      ToolchainResolution:   All execution platforms have been assigned a @bazel_tools//tools/jdk:toolchain_type toolchain, stopping
      ToolchainResolution: Recap of selected @bazel_tools//tools/jdk:toolchain_type toolchains for target platform @buildkite_config//config:platform:
      ToolchainResolution:   Selected @rules_java_builtin//toolchains:toolchain_java8 to run on execution platform @buildkite_config//config:platform
(02:20:47) INFO: ToolchainResolution: Target platform @buildkite_config//config:platform: Selected execution platform @buildkite_config//config:platform, type @bazel_tools//tools/jdk:toolchain_type -> toolchain @rules_java_builtin//toolchains:toolchain_java8
(02:20:48) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/c2424c3924a05e9cdbea7e5a3704ee76/external/docs_deps_sphinx/BUILD.bazel:22:11: @docs_deps_sphinx//:pkg depends on @docs_deps_babel//:pkg in repository @docs_deps_babel which failed to fetch. no such package '@docs_deps_babel//': whl_library docs_deps_babel failed: Collecting babel==2.12.1 (from -r /tmp/tmpid1jb1s6 (line 1))
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
                                              0.0/10.1 MB 742.0 kB/s eta 0:00:14
 (ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    babel==2.12.1 from https://files.pythonhosted.org/packages/df/c4/1088865e0246d7ecf56d819a233ab2b72f7d6ab043965ef327d0731b5434/Babel-2.12.1-py3-none-any.whl (from -r /tmp/tmpid1jb1s6 (line 1)):
        Expected sha256 b4246fb7677d3b98f501a39d43396d3cafdc8eadb045f4a31be01863f655c610
        Expected     or cc2d99999cd01d44420ae725a21c9e3711b3aadc7976d6147f622d8581963455
             Got        9aebf7fab2060a111cd0b2757c0de20316b41dd0235ce5d6a2ce994cf43e6e4e

```

Steps:
```
git clone -v https://github.com/bazelbuild/rules_python.git
git reset 9b73d02ae1756ef52e35ec78b3b114b6e4db460f --hard
export USE_BAZEL_VERSION=206bec1ee2309ef64309fc3eb1c35576f7f6c37c
bazel build keep_going -- ... @rules_python//examples/wheel/...
```
 Culprit : [32cc97e0a9a5810ab5469708f768666022c27642](https://github.com/bazelbuild/bazel/commit/32cc97e0a9a5810ab5469708f768666022c27642)

CC  Greenteam @comius

**Comment by Wyverald** [comment]
This particular one seems to have been fixed.
