### ISSUE TITLE
incompatible_depset_union

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_python#175]
This command: `bazel build ... --incompatible_depset_union`
fails with the message:

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-5r85/bazel-downstream-projects/rules_python/experimental/examples/wheel/BUILD:65:1: in py_wheel rule //experimental/examples/wheel:customized:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-5r85/bazel-downstream-projects/rules_python/experimental/examples/wheel/BUILD", line 65
  | py_wheel(name = 'customized')
  | File "/var/lib/buildkite-agent/builds/bk-docker-5r85/bazel-downstream-projects/rules_python/experimental/python/wheel.bzl", line 145, in _py_wheel_impl
  | inputs.union([description_file])
  | depset method `.union` has been removed. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations.
```

Please take a look, we're going to flip the flag soon.

**Comment by pstradomski** [comment]
Should be straightforward to fix. I'll try to send a PR by the end of the week
