### ISSUE TITLE
pip extras_require fails

### ISSUE THREAD

**Issue by jpvelez** [bazelbuild/rules_python#185]
Hi there!

I have the following in my `requirements.txt`:
```
apache-beam[gcp]
```

I have a target that imports this as a requirement. When I got to build the target, I get the following error:

```
bazel build //:main
INFO: Invocation ID: 37e2bf96-1e58-4e1e-ba62-4f553a6106c6
DEBUG: Rule 'io_bazel_rules_python' modified arguments {"shallow_since": "1556033974 -0400"}
ERROR: /Users/jpvelez/repos/bazel-python-bug/BUILD:4:1: Traceback (most recent call last):
	File "/Users/jpvelez/repos/bazel-python-bug/BUILD", line 4
		py_binary(name = "main", srcs = ["main.py"], d...]")])
	File "/Users/jpvelez/repos/bazel-python-bug/BUILD", line 10, in py_binary
		requirement("apache_beam[gcp]")
	File "/private/var/tmp/_bazel_jpvelez/38a707cf9d0f20110a0d780b5b663df2/external/pip/requirements.bzl", line 418, in requirement
		fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'apache_beam[gcp]'
ERROR: Skipping '//:main': no such target '//:main': target 'main' not declared in package '' defined by /Users/jpvelez/repos/bazel-python-bug/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:main': target 'main' not declared in package '' defined by /Users/jpvelez/repos/bazel-python-bug/BUILD
INFO: Elapsed time: 15.022s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

This also happens with any library that depends on `apache-beam[gcp]`, like `tensorflow-transform`.  

The [gcp] git is called an extras_require, in pip parlance.

To reproduce the bug, clone the following repo and run `bazel build //:main`:
https://github.com/jpvelez/bazel-python-bug/tree/20af1e25594ccb77f2b2fb3b240829c0e714c3ad

**Comment by pcn** [comment]
Last time I dived into this, it was a result of this: https://github.com/bazelbuild/rules_python/pull/90

**Comment by thundergolfer** [comment]
With the newer `pip_install` I was able to install and run apache_beam (version: 2.29.0) successfully.

I did not test the `[gcp]` component but if we look at the BUILD file for the dependency in `external/pypi/pypi__apache_beam/BUILD.bazel` we see: 

```
py_library(
    name="pypi__apache_beam",
    srcs=glob(["**/*.py"], allow_empty=True),
    data=glob(
        ["**/*"], exclude=["*.whl", "**/*.py", "**/* *", "BUILD.bazel", "WORKSPACE"]
    ),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports=["."],
    deps=[
        "//pypi__avro_python3",
        "//pypi__cachetools",
        "//pypi__crcmod",
        "//pypi__dill",
        "//pypi__fastavro",
        "//pypi__future",
        "//pypi__google_apitools",
        "//pypi__google_auth",
        "//pypi__google_cloud_bigquery",
        "//pypi__google_cloud_bigtable",
        "//pypi__google_cloud_core",
        "//pypi__google_cloud_datastore",
        "//pypi__google_cloud_dlp",
        "//pypi__google_cloud_language",
        "//pypi__google_cloud_pubsub",
        "//pypi__google_cloud_spanner",
        "//pypi__google_cloud_videointelligence",
        "//pypi__google_cloud_vision",
        "//pypi__grpcio",
        "//pypi__grpcio_gcp",
        "//pypi__hdfs",
        "//pypi__httplib2",
        "//pypi__numpy",
        "//pypi__oauth2client",
        "//pypi__protobuf",
        "//pypi__pyarrow",
        "//pypi__pydot",
        "//pypi__pymongo",
        "//pypi__python_dateutil",
        "//pypi__pytz",
        "//pypi__requests",
        "//pypi__typing_extensions",
    ],
)
```

which includes all the extra GCP packages. 

(Note, the Bazel rules are pretty slow to load this package, probably on account of how many dependencies it pulls in).

**Comment by thundergolfer** [comment]
Will close this issue as resolved by the newer `pip_install` (demo'd above) and `pip_parse` functionality.
