### ISSUE TITLE
Broken by incompatible change in Bazel 0.27

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#191]
Building a project with bazel at head, I get

```
ERROR: /usr/local/google/home/brandjon/.cache/bazel/_bazel_brandjon/27ebe2e9c0501b3e398c2702c3a8ceeb/external/io_bazel_rules_python/python/pip.bzl:39:25: Traceback (most recent call last):
	File "/usr/local/google/home/brandjon/.cache/bazel/_bazel_brandjon/27ebe2e9c0501b3e398c2702c3a8ceeb/external/io_bazel_rules_python/python/pip.bzl", line 37
		repository_rule(attrs = {"requirements": attr.la...")}, ...)
	File "/usr/local/google/home/brandjon/.cache/bazel/_bazel_brandjon/27ebe2e9c0501b3e398c2702c3a8ceeb/external/io_bazel_rules_python/python/pip.bzl", line 39, in repository_rule
		attr.label(allow_files = True, mandatory = Tr..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
```

This apparently wasn't caught by any tests in rules_python. Migration tracking issue is bazelbuild/bazel#5818.

**Comment by brandjon** [comment]
Gah, my mistake -- I was apparently using a workspace with an exceedingly old version of rules_python.
