### ISSUE TITLE
Pip fails dictionary lookup.

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_python#20]
Requirements file of `boto3==1.4.7` fails with
```
ERROR: /private/var/tmp/_bazel_edwardmcfarlane/ad32b996cb424fa4cc44a5c86220cb2f/external/pypi__boto3_1_4_7/BUILD:6:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_edwardmcfarlane/ad32b996cb424fa4cc44a5c86220cb2f/external/pypi__boto3_1_4_7/BUILD", line 6
		py_library(name = "pkg", srcs = glob(["**/*.p..."]), <3 more arguments>)
	File "/private/var/tmp/_bazel_edwardmcfarlane/ad32b996cb424fa4cc44a5c86220cb2f/external/pypi__boto3_1_4_7/BUILD", line 13, in py_library
		requirement("botocore>=1.7.0,<1.8.0")
	File "/private/var/tmp/_bazel_edwardmcfarlane/ad32b996cb424fa4cc44a5c86220cb2f/external/pip/requirements.bzl", line 150, in requirement
		_requirements[name]
key "botocore>=1.7.0,<1.8.0" not found in dictionary.
```

**Comment by afking** [comment]
Would be nice to be to fix all sub dependencies. For example `botocore==1.7.22` that would satisfy version range.

**Comment by mattmoor** [comment]
Hmm, this is an artifact of how we are parsing the `metadata.json` from the `.whl` file, typically this version information is expressed differently.  I will try to TAL and see how hard a fix this is.

**Comment by mattmoor** [comment]
Ok, I think that this is hopefully just switching things over to use `re.split` and expanding the character set.  I'll hopefully have a PR you can test shortly.  (famous last words)

**Comment by afking** [comment]
@mattmoor awesome! Works, thanks for the quick fix.

**Comment by afking** [comment]
@mattmoor think it might be an error on my side but failing to build on Ubuntu, mac is working fine. Fails with:
```
bazel build //:my_python_lib
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip//': pip_import failed:  (ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
)
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip//': pip_import failed:  (ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
)
INFO: Elapsed time: 0.602s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
Am I not setting up the workspace properly?

**Comment by mattmoor** [comment]
Hmm, that's interesting.  It should be picking up the `wheel` package from the `piptool.par`, as specified in the `requirements.txt` [here](https://github.com/bazelbuild/rules_python/blob/master/python/requirements.txt#L2).

**Comment by afking** [comment]
Installed pip locally. Build got further now but still has errors:
```sh
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip//': pip_import failed: Collecting botocore<1.8.0,>=1.7.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading botocore-1.7.25-py2.py3-none-any.whl (3.7MB)
  Saved ./botocore-1.7.25-py2.py3-none-any.whl
Collecting boto3==1.4.7 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 2))
  Downloading boto3-1.4.7-py2.py3-none-any.whl (128kB)
  Saved ./boto3-1.4.7-py2.py3-none-any.whl
Collecting lxml==4.0.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 3))
  Downloading lxml-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl (5.3MB)
  Saved ./lxml-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting requests==2.18.4 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
  Saved ./requests-2.18.4-py2.py3-none-any.whl
Collecting beautifulsoup4==4.6.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 5))
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
  Saved ./beautifulsoup4-4.6.0-py2-none-any.whl
Collecting configparser==3.5.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 6))
  Downloading configparser-3.5.0.tar.gz
Collecting python-u2flib-host==3.0.2 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 7))
  Downloading python-u2flib-host-3.0.2.tar.gz
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
  Saved ./python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading docutils-0.14-py2-none-any.whl (543kB)
  Saved ./docutils-0.14-py2-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
  Saved ./jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3==1.4.7->-r /root/go/src/company.com/repo/main//requirements.txt (line 2))
  Downloading s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
  Saved ./s3transfer-0.1.11-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
  Saved ./chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
  Saved ./certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
  Saved ./urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
  Saved ./idna-2.6-py2.py3-none-any.whl
Collecting hidapi>=0.7.99 (from python-u2flib-host==3.0.2->-r /root/go/src/company.com/repo/main//requirements.txt (line 7))
  Downloading hidapi-0.7.99.post20.tar.gz (51kB)
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Tempita/_tempita.py because it changed.
    [ 1/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Code.py
    [ 2/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/FlowControl.py
    [ 3/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Lexicon.py
    [ 4/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Parsing.py
    [ 5/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Pythran.py
    [ 6/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Scanning.py
    [ 7/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Visitor.py
    [ 8/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Actions.py
    [ 9/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.py
    [10/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Runtime/refnanny.pyx
    [11/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Tempita/_tempita.py
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.c:19:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WzaNk6/hidapi/setup.py", line 123, in <module>
        install_requires = ['setuptools>=19.0'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
 (Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WzaNk6/hidapi/
)
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip//': pip_import failed: Collecting botocore<1.8.0,>=1.7.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading botocore-1.7.25-py2.py3-none-any.whl (3.7MB)
  Saved ./botocore-1.7.25-py2.py3-none-any.whl
Collecting boto3==1.4.7 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 2))
  Downloading boto3-1.4.7-py2.py3-none-any.whl (128kB)
  Saved ./boto3-1.4.7-py2.py3-none-any.whl
Collecting lxml==4.0.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 3))
  Downloading lxml-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl (5.3MB)
  Saved ./lxml-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting requests==2.18.4 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
  Saved ./requests-2.18.4-py2.py3-none-any.whl
Collecting beautifulsoup4==4.6.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 5))
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
  Saved ./beautifulsoup4-4.6.0-py2-none-any.whl
Collecting configparser==3.5.0 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 6))
  Downloading configparser-3.5.0.tar.gz
Collecting python-u2flib-host==3.0.2 (from -r /root/go/src/company.com/repo/main//requirements.txt (line 7))
  Downloading python-u2flib-host-3.0.2.tar.gz
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
  Saved ./python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading docutils-0.14-py2-none-any.whl (543kB)
  Saved ./docutils-0.14-py2-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from botocore<1.8.0,>=1.7.0->-r /root/go/src/company.com/repo/main//requirements.txt (line 1))
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
  Saved ./jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3==1.4.7->-r /root/go/src/company.com/repo/main//requirements.txt (line 2))
  Downloading s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
  Saved ./s3transfer-0.1.11-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
  Saved ./chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
  Saved ./certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
  Saved ./urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests==2.18.4->-r /root/go/src/company.com/repo/main//requirements.txt (line 4))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
  Saved ./idna-2.6-py2.py3-none-any.whl
Collecting hidapi>=0.7.99 (from python-u2flib-host==3.0.2->-r /root/go/src/company.com/repo/main//requirements.txt (line 7))
  Downloading hidapi-0.7.99.post20.tar.gz (51kB)
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Tempita/_tempita.py because it changed.
    [ 1/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Code.py
    [ 2/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/FlowControl.py
    [ 3/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Lexicon.py
    [ 4/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Parsing.py
    [ 5/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Pythran.py
    [ 6/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Scanning.py
    [ 7/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Compiler/Visitor.py
    [ 8/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Actions.py
    [ 9/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.py
    [10/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Runtime/refnanny.pyx
    [11/11] Cythonizing /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Tempita/_tempita.py
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-CvT2_Y/Cython-0.27.1/Cython/Plex/Scanners.c:19:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WzaNk6/hidapi/setup.py", line 123, in <module>
        install_requires = ['setuptools>=19.0'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
 (Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WzaNk6/hidapi/
)
INFO: Elapsed time: 23.916s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Ubuntu 17.04
Python 2.7.13

**Comment by mattmoor** [comment]
I don't know why I didn't see this before, but this very likely needs `python-dev` installed so that `Python.h` is available.  IIRC, this should fix this: `apt-get install python-dev`.

IDK that our `piptool.par` can ever fully achieve a state where we have no external deps factoring in situations like this, where `setup.py` expects all kind of toolchain pre-installed...
