### ISSUE TITLE
//external:pypi: no such attribute 'requirements' in 'pip_repository' rule

### ISSUE THREAD

**Issue by 6eanut** [bazelbuild/rules_python#2093]
i want to build tensorflow 2.15.0 by bazel 6.1.0.

```
$ bazel build //tensorflow/tools/pip_package:build_pip_package --local_ram_resources=2048 --jobs=32
INFO: Reading 'startup' options from /home/tf2150/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=121
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/tf2150/venv00/bin/python3 --action_env PYTHON_LIB_PATH=/home/tf2150/venv00/lib/python3.11/site-packages --python_path=/home/tf2150/venv00/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/tf2150/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/tf2150/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/tf2150/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/tf2150/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository python instantiated at:
  /home/tf2150/tensorflow/WORKSPACE:36:27: in <toplevel>
  /home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/repositories.bzl:608:22: in python_register_toolchains
Repository rule toolchain_aliases defined at:
  /home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/private/toolchains_repo.bzl:241:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python':
   Traceback (most recent call last):
        File "/home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/private/toolchains_repo.bzl", line 149, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/private/toolchains_repo.bzl", line 333, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: /home/tf2150/tensorflow/WORKSPACE:36:27: fetching toolchain_aliases rule //external:python: Traceback (most recent call last):
        File "/home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/private/toolchains_repo.bzl", line 149, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/home/tf2150/.cache/bazel/_bazel_tf2150/60eb52f288784e0041f9e5b9bad9cb04/external/rules_python/python/private/toolchains_repo.bzl", line 333, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch riscv64
ERROR: Error computing the main repository mapping: no such package '@python//': No platform declared for host OS linux on arch riscv64
Loading:
```

then ,i change the WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "9d04041ac92a0985e344235f5d946f71ac543f1b1565f2cdbc9a2aaee8adf55b",
    strip_prefix = "rules_python-0.26.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()
```
to
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "778aaeab3e6cfd56d681c89f5c10d7ad6bf8d2f1a72de9de55b23081b2d31618",
    strip_prefix = "rules_python-0.34.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.34.0/rules_python-0.34.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()
```

but meet
```
$ bazel build //tensorflow/tools/pip_package:build_pip_package --local_ram_resources=2048 --jobs=32
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server (4008936) after 10 seconds ...
INFO: Reading 'startup' options from /home/tf2150/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=121
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/tf2150/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/tf2150/venv00/bin/python3 --action_env PYTHON_LIB_PATH=/home/tf2150/venv00/lib/python3.11/site-packages --python_path=/home/tf2150/venv00/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/tf2150/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/tf2150/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/tf2150/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/tf2150/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: /home/tf2150/tensorflow/WORKSPACE:61:10: //external:pypi: no such attribute 'requirements' in 'pip_repository' rule
ERROR: Error computing the main repository mapping: Encountered error while reading extension file 'requirements.bzl': no such package '@pypi//': error loading package 'external': Could not load //external package
Loading:
```

**Comment by groodt** [comment]
It looks like you are attempting to build tensorflow and encountering issues with the build. Please raise your issue on the tensorflow tracker.

It's not clear from this issue report that any bug has been encountered with rules_python.
