### ISSUE TITLE
bazel crashes on invalid `rules_python` repository names

### ISSUE THREAD

**Issue by martingms** [bazelbuild/rules_python#2493]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

N/A

### Description

 A clear and concise description of the problem...
I'm trying to upgrade to bazel 8.0.0, but building any target in my fairly vanilla repo results in a bazel crash on what seems like invalid `rules_python` repository names.

@fmeum suggested that this might be a `rules_python` bug [on slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1733839594904599?thread_ts=1733837499.011179&cid=CA31HN1T3).

## 🔥 Exception or Error

<pre><code>
java.lang.RuntimeException: Unrecoverable error while evaluating node '[/home/mg/.cache/bazel/_bazel_mg/e0890c4bddef48fe519e71582abd3fc5]/[external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu]' (requested by nodes 'FILE:[/home/mg/.cache/bazel/_bazel_mg/e0890c4bddef48fe519e71582abd3fc5]/[external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.concurrent.CompletionException: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name 'rules_python~~python~python_3_11_x86_64-unknown-linux-gnu': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '+'
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:204)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2451)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2449)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2432)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:107)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:57)
	at com.google.devtools.build.lib.cmdline.RepositoryName.createUnvalidated(RepositoryName.java:107)
	at com.google.devtools.build.lib.rules.repository.RepositoryFunction.addExternalFilesDependencies(RepositoryFunction.java:408)
	at com.google.devtools.build.lib.skyframe.ExternalFilesHelper.maybeHandleExternalFile(ExternalFilesHelper.java:287)
	at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:61)
	at com.google.devtools.build.lib.skyframe.FileStateFunction.compute(FileStateFunction.java:35)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	... 7 more
Caused by: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name 'rules_python~~python~python_3_11_x86_64-unknown-linux-gnu': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '+'
	at com.google.devtools.build.lib.cmdline.LabelParser.syntaxErrorf(LabelParser.java:208)
	at com.google.devtools.build.lib.cmdline.RepositoryName.validate(RepositoryName.java:191)
	at com.google.devtools.build.lib.cmdline.RepositoryName.lambda$static$0(RepositoryName.java:71)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 8.0.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Dec 09 18:00:43 2024 (1733767243)
Build timestamp: 1733767243
Build timestamp as int: 1733767243
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
1.0.0
  </code>
</pre>

**Comment by aignas** [comment]
This looks like some stale cache. Have you tried doing `bazel clean --expunge`? We don't have any mentions of `~` in our repo, so I am curious why this is happening.

**Comment by rickeylev** [comment]
Yeah, we don't manually construct any repo names with `~` or `+` in them. That's part of the Bazel internal naming.

Perhaps this is related to the switch from `~` to `+` in the canonical names?

**Comment by martingms** [comment]
> This looks like some stale cache. Have you tried doing `bazel clean --expunge`? We don't have any mentions of `~` in our repo, so I am curious why this is happening.

Yes, I ran `bazel clean --expunge`, rm'd `MODULE.bazel.lock` and even nuked my whole `~/.cache/bazel` directory. Just did it again to make sure.

To be clear my only indication that this is related to `rules_python` is fmeums comment and that it's a rules_python repo it crashes on! I'll see if I can comment out some other rulesets that might be using `rules_python` on old versions or something I guess!

**Comment by martingms** [comment]
Some more digging (with a `grep -r "rules_python~~python~python_3_11_x86_64-unknown-linux-gnu" /` :sweat_smile:), and I found a single reference (apart from some bazel log files about the crashes):
`~/<my-repo>/.venv/pyvenv.cfg:home = /home/mg/.cache/bazel/_bazel_mg/e0890c4bddef48fe519e71582abd3fc5/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/bin`
which is a venv created by `rules_py`'s `py_venv`... Nuking that fixed it.

Sorry to bother you with someone else's bug!
It seems like it shouldn't crash bazel anyway I guess, so for anyone seeing this later I opened an issue there too: https://github.com/bazelbuild/bazel/issues/24621
