### ISSUE TITLE
Adding pip_import to tensorflow_graphics

### ISSUE THREAD

**Issue by ataiya** [bazelbuild/rules_python#299]
Added the following to the bottom of this [WORKSPACE](https://github.com/tensorflow/graphics/blob/master/WORKSPACE) file, and created a `requirements.txt` in the same folder:
```
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# Only needed if using the packaging rules.
load("@rules_python//python:pip.bzl", "pip_repositories")
pip_repositories()

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

load("@rules_python//python:pip.bzl", "pip_import")

# pip install dependencies for Bazel
pip_import(
    name = "python_deps",
    requirements = "//:requirements.txt",
)

load("@python_deps//:requirements.bzl", "pip_install")
pip_install()
```

Getting the error:
```
(python3) ~/dev/pointnet/graphics: bazel build //tensorflow_graphics
INFO: Call stack for the definition of repository 'python_deps' which is a pip_import (rule definition at /home/atagliasacchi_google_com/.cache/bazel/_bazel_atagliasacchi_google_com/6a7b0435e2e6d2abcb81e0c19cfd9b63/external/
rules_python/python/pip.bzl:42:14):
 - <builtin>
 - /home/atagliasacchi_google_com/dev/pointnet/graphics/WORKSPACE:64:1
ERROR: An error occurred during the fetch of repository 'python_deps':
   Traceback (most recent call last):
        File "/home/atagliasacchi_google_com/.cache/bazel/_bazel_atagliasacchi_google_com/6a7b0435e2e6d2abcb81e0c19cfd9b63/external/rules_python/python/pip.bzl", line 26
                repository_ctx.execute(<1 more arguments>)
        File "/home/atagliasacchi_google_com/.cache/bazel/_bazel_atagliasacchi_google_com/6a7b0435e2e6d2abcb81e0c19cfd9b63/external/rules_python/python/pip.bzl", line 32, in repository_ctx.execute
                repository_ctx.path(<1 more arguments>)
Unable to load package for //:requirements.txt: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/atagliasacchi_google_com/dev/pointnet/graphics
ERROR: no such package '@python_deps//': Traceback (most recent call last):
        File "/home/atagliasacchi_google_com/.cache/bazel/_bazel_atagliasacchi_google_com/6a7b0435e2e6d2abcb81e0c19cfd9b63/external/rules_python/python/pip.bzl", line 26
                repository_ctx.execute(<1 more arguments>)
        File "/home/atagliasacchi_google_com/.cache/bazel/_bazel_atagliasacchi_google_com/6a7b0435e2e6d2abcb81e0c19cfd9b63/external/rules_python/python/pip.bzl", line 32, in repository_ctx.execute
                repository_ctx.path(<1 more arguments>)
Unable to load package for //:requirements.txt: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/atagliasacchi_google_com/dev/pointnet/graphics
INFO: Elapsed time: 0.271s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

But [your documentation](https://github.com/bazelbuild/rules_python) does not mention anything about adding a BUILD referencing `requirements.txt`?'

**hack**: adding an empty BUILD file alongside WORKSPACE seemed to have resolved the issue for now (but this is undocumented, and relatively weird to have as its sole purpose is to have this rule work)

**Comment by thundergolfer** [comment]
> and relatively weird to have as its sole purpose is to have this rule work

It's not the sole purpose of the `BUILD` file. Putting a `BUILD` file in the directory makes that directory a package from Bazel's perspective, and then allows referencing of the labels within that package. [Files in a package are implicitly labels](https://docs.bazel.build/versions/master/build-ref.html#labels), so `//:requirements.txt` works.

Without the `BUILD` file, `//:requirements.txt` is not a valid label, and you get the "BUILD file not found in any of the following directories." error.

**Comment by ataiya** [comment]
Right, from a user perspective this is unexpected behavior though (requires as much work as mentioning it in the documentation)

**Comment by thundergolfer** [comment]
I'd hesitate to add it to the `README` because this behaviour isn't `rules_python` specific, it's Bazel specific. Generally, no file can be used within Bazel if it doesn't reside in a Bazel package.

**Comment by ataiya** [comment]
I guess my issue acts as "searchable" documentation at this point.

**Comment by thundergolfer** [comment]
It does 🙂. Happy for me to close this out?

**Comment by ataiya** [comment]
Of course ;)
