### ISSUE TITLE
rules_python failing on Bazel CI after new googleapis-common-protos release

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_python#321]
https://pypi.org/project/googleapis-common-protos/1.52.0/ was out since Jun 4, 2020.

rules_python started to fail at the same time:
https://buildkite.com/bazel/rules-python-python/builds/821
```
(00:23:22) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/examples_extras/requirements.bzl:243:9: Traceback (most recent call last):
	File "/workdir/examples/extras/BUILD", line 22
		py_test(name = "extras_test", <3 more arguments>)
	File "/workdir/examples/extras/BUILD", line 29, in py_test
		requirement(<1 more arguments>)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/examples_extras/requirements.bzl", line 243, in requirement
		fail(<1 more arguments>)
Could not find pip-provided dependency: 'googleapis-common-protos[grpc]'
```

**Comment by gergelyfabian** [comment]
Adding googleapis-common-protos==1.51.0 to requirements.txt fixes this issue. Will send a PR.
