### ISSUE TITLE
Is it possible to pass to pip additional arguments?

### ISSUE THREAD

**Issue by jaksky** [bazelbuild/rules_python#332]
Hello,

from the code I see that it should be possible to pass to pip additional arguments via `extra_pip_args`  from code https://github.com/bazelbuild/rules_python/blob/master/python/pip.bzl#L44  and around though I am struggling to find a correct way.
```
pip_import(
    extra_pip_args = ["--index-url=https://usr:pwd@domain.com/repository/pypi/simple"],
    name = "python_deps",
    timeout = 1200,
    requirements = "//:requirements.txt"
)
```

Can someone suggest?

**Comment by thundergolfer** [comment]
@jaksky What problem/error are you experiencing, if any?

**Comment by jaksky** [comment]
```
ERROR: no such package '@python_deps//': pip_import failed: Collecting eventregistry==8.6 (from -r /Users/jakub/Development/GIT_REPO/test/requirements.txt (line 2))
User for domain.com:  (Exception:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/commands/wheel.py", line 199, in run
    if not wb.build():
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/private/var/tmp/_bazel_jakub/6f741e64cb7872feb5c9b156395a088d/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 181, in handle_401
    username = six.moves.input("User for %s: " % parsed.netloc)
EOFError: EOF when reading a line
```

It seems that it is because pretty legacy pip used and  is related to https://github.com/bazelbuild/rules_python/pull/263

I am trying to set different index repository than pypi.org

**Comment by jaksky** [comment]
Sorry, I resolved the issue using https://github.com/pypa/pip/issues/51
