### ISSUE TITLE
python runfiles don't put 'Package Data' in the right place

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/rules_python#408]
# 🐞 bug report

### Affected Rule

I'm not sure where the cause is, maybe in providers for the new `requirement` rule?

### Is this a regression?

Do not believe so. Happens with both interpreter-in-repository and host interpreter (in empty virtualenv).

### Description

Repro is based in https://github.com/dhalperi/bazel_python, where you can try WORKSPACE or WORKSPACE.hostpython to use in-tree interpreter or host interpreter (but in an empty virtualenv).

I have a simple `py_binary` rule to run the equivalent of `jupyter notebook` via bazel, which has only one dependency: `requirement('jupyter')`.

It actually mostly works. However, when I try to download a notebook, say as PDF, I get a `500 Internal Server` error with a stack trace indicating that `nbconvert` library can't find its templates.

The templates are in `notebook.runfiles`: `/Users/dan/git-workspace/dhalperi/bazel_python/bazel-bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert-6.0.7.data/data/share/jupyter/nbconvert/templates`

However, Python expects them to be at some standard python location, something like `<interpreter>/share/jupyter/...`, in addition to a variety of global locations:

```
  /Users/dan/Library/Jupyter 
  /private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/external/python_interpreter/python_install/share/jupyter
  /usr/local/share/jupyter
  /usr/share/jupyter
```
I guess I can't quite imagine how this specific method could work with host interpreter.

My guess is that:

* we need to set up some environment variable to tell python where to look for the accumulated `share/foo` things that are in each package's `.data` area.
* we need to add more symlinks into the interpreter part of runfiles
* ... something else?

## 🔬 Minimal Reproduction

Check out https://github.com/dhalperi/bazel_python/tree/rules-python-%23408, and using either `WORKSPACE` (for in-tree interpreter) or `WORKSPACE.hostpython` (for host python interpreter, make sure you setup an empty python3 virtualenv or equivalent):

Run `bazel run //notebook`

Create a new notebook, then try to download it via `File` > `Download as..` > `PDF` (e.g.). You will get redirected to a `500 Internal Server` error.

If you don't get this error, please make sure that the global paths mentioned above do not contain the `share/jupyter` folder. Otherwise, you are likely picking up some libraries outside of the Bazel tree, which is the entire thing I'm trying to eliminate.

## 🔥 Exception or Error

<pre><code>
    Traceback (most recent call last):
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 535, in get
        value = obj._trait_values[self.name]
    KeyError: 'template_paths'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__tornado/tornado/web.py", line 1704, in _execute
        result = await result
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__tornado/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__notebook/notebook/nbconvert/handlers.py", line 92, in get
        exporter = get_exporter(format, config=self.config, log=self.log)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__notebook/notebook/nbconvert/handlers.py", line 67, in get_exporter
        Exporter = get_exporter(format)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
        for path in map(Path, self.template_paths):
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 575, in __get__
        return self.get(obj, cls)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 538, in get
        default = obj.trait_defaults(self.name)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 1578, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__traitlets/traitlets/traitlets.py", line 975, in __call__
        return self.func(*args, **kwargs)
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 518, in _template_paths
        template_names = self.get_template_names()
      File "/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/execroot/bazel_python/bazel-out/darwin-fastbuild/bin/notebook/notebook.runfiles/pip/pypi__nbconvert/nbconvert/exporters/templateexporter.py", line 601, in get_template_names
        raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
    ValueError: No template sub-directory with name 'latex' found in the following paths:
    	/Users/dan/Library/Jupyter
    	/private/var/tmp/_bazel_dan/86075a8c64916cc92a0fec233d0053c0/external/python_interpreter/python_install/share/jupyter
    	/usr/local/share/jupyter
    	/usr/share/jupyter
</code></pre>

## 🌍  Your Environment

**Operating System:**

macOS 10.15.7 (19H114) [Catalina]

**Output of `bazel version`:**

```
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
```

**Rules_python version:**

Authoritatively, refer to the WORKSPACE in the repro repository, I believe it is the sha of the `0.1.0` release.

`https://github.com/bazelbuild/rules_python/archive/c8c79aae9aa1b61d199ad03d5fe06338febd0774.tar.gz`

**Anything else relevant?**

I saw #63, but that issue clearly predates the switch to `rules_python_external`. I doubt it's relevant?

I am happy to do more deeper legwork, I'm just not sure to start. (But I will probably keep reading in the background), If you have any ideas, find me here or on bazelbuild slack #python.

**Comment by groodt** [comment]
I ran into the very same issue and hacked around it as follows.

```
    jupyterlab_version = jupyterlab.__version__
    jupyterlab_package_dir = Path(jupyterlab.__file__).parents[1]
    data_dir = str(
        jupyterlab_package_dir
        / f"jupyterlab-{jupyterlab_version}.data"
        / "data"
        / "share"
        / "jupyter"
        / "lab"
    )
```
Then later, supply the app-dir when launching Jupyter Lab.

The problem here is that Python data files are used to ship arbitrary files and copy them to the sys.path:
https://docs.python.org/2/distutils/setupscript.html#installing-additional-files

I don't know if `rules_python` storing them in a `.data` directory is the best that can be done, or if they should be included alongside the rest of the code. Ultimately, it is a bit of a hermetic mess I think, because things like the jupyter packages can ship arbitrary files to a *shared* location. So it's possible for 2 different packages to ship files that end up on your sys.path with a common prefix (i.e. share/jupyter). It's probably not possible to support such behaviour with Bazel if I had to guess.

**Comment by thundergolfer** [comment]
From initial poking around, looks to me like the `ValueError` comes from the unhappy interaction of the Bazel runfiles setup and this code:

[`templateexporter.get_template_names`](https://github.com/jupyter/nbconvert/blob/7b53502/nbconvert/exporters/templateexporter.py#L612) which uses [`jupyter_core.paths`](https://github.com/jupyter/jupyter_core/blob/0870271a25fede7a37f4f6932d38293e6cc5c04b/jupyter_core/paths.py#L135)

**Comment by dhalperi** [comment]
Hmm. Thanks @groodt @thundergolfer

It sounds like the right answer is that Bazel isn't trying to handle this shared functionality, but we can likely work around such issues in a pip-library-specific way. If so, I guess no bug on the `rules_python` side :).

Given that I will close this.

(But also, I will update the linked repo when I fix the particular Jupyter issue. Thanks both for the tips!!)

**Comment by EricCousineau-TRI** [comment]
Late question - what is a suggested workaround for a pip-library-specific way?
Is there an affordance to have hooks with `rules_python`?
Or do we write a genrule to aggregate the shared data?

(I'm asking specifically to have the `jupyter lab` command in a Bazel env work with minimal custom hacks / workarounds; curious if others have found out the right way)

**Comment by EricCousineau-TRI** [comment]
using @groodt's https://github.com/bazelbuild/rules_python/issues/408#issuecomment-768680095, this is how I supply `--app-dir`, which works for at least vanilla `jupyter-lab`

https://github.com/EricCousineau-TRI/bazel_jupyter_example/blob/c837e2f1707e092d05a3538d454951986599f6df/tools/jupyter/jupyter_bazel.py#L26-L30
