### ISSUE TITLE
ModuleNotFoundError when depending on multiple Google projects

### ISSUE THREAD

**Issue by JoshuaCrestone** [bazelbuild/rules_python#431]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`py_library`

### Is this a regression?

I think so. This was working correctly with [rules_python_external](https://github.com/dillon-giacoppo/rules_python_external). But after upgrading my requirements.txt and switching to the latest version of rules_python, I have started to see the issue again.

### Description

I have a `py_library` the following py_library rule:

```
py_library(
  name = "dataflow",
  srcs = ["dataflow.py"],
  deps = [
    requirement("google-auth"),
    requirement("google-auth-httplib2"),
    requirement("google-api-core"),
    requirement("google-api-python-client"),
    requirement("python-dateutil"),
  ],
  visibility = [
    "//crestone/luigi:__subpackages__",
  ],
)
```

And get the following error:
```
Traceback (most recent call last):
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/Crestone/crestone/gcp/dataflow_test.py", line 8, in <module>
    from crestone.gcp import dataflow
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/Crestone/crestone/gcp/dataflow.py", line 12, in <module>
    from googleapiclient import discovery
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/pip/pypi__google_api_python_client/googleapiclient/discovery.py", line 50, in <module>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core'
```

## 🔬 Minimal Reproduction

I have included the WORKSPACE, along with the BUILD file and the Python code that is triggering the issue:
https://github.com/JoshuaCrestone/RulesPythonImportIssues

## 🔥 Exception or Error
<pre><code>
Traceback (most recent call last):
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/Crestone/crestone/gcp/dataflow_test.py", line 8, in <module>
    from crestone.gcp import dataflow
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/Crestone/crestone/gcp/dataflow.py", line 12, in <module>
    from googleapiclient import discovery
  File "/home/joshua/.cache/bazel/_bazel_joshua/3a56d58236696fc82ab667141944da13/sandbox/linux-sandbox/53/execroot/Crestone/bazel-out/k8-fastbuild/bin/crestone/gcp/dataflow_test.runfiles/pip/pypi__google_api_python_client/googleapiclient/discovery.py", line 50, in <module>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Build label: 3.1.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 17 09:48:11 2020 (1597657691)
Build timestamp: 1597657691
Build timestamp as int: 1597657691
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.1.0
  </code>
</pre>

**Anything else relevant?**

**Comment by husafan** [comment]
Sorry to bother - have you had a chance to look into this at all?

**Comment by thundergolfer** [comment]
Not a problem at all @husafan, I'm here to be pinged 🙂 . 

I've created https://github.com/thundergolfer-playground/rules_python-issue-431 to help investigate this issue. I'm having trouble using the reproduction repo linked in the issue description. 

The requirements file looks to include for more packages than should be necessary for a reproduction, and at least one is failing to install for me. Error:

```
    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
```

The code also includes source files which I don't think are in the reproduction repo, for example:

```
from crestone.gcp import dataflow
from crestone.testing import gcp_responses
```

To be able to better investigate the problem, cutting away the reproduction repo until we have a minimal reproduction of the issue would be great.

**Comment by thundergolfer** [comment]
As we're seeing an import error

> ModuleNotFoundError: No module named 'google.api_core'

the source modules in the reproduction can be pretty minimal. Don't need application behaviour like `DataflowMonitor`.

**Comment by husafan** [comment]
Thank you for taking the time to look into this! Sorry for not confirming the test repo first.

I have updated https://github.com/JoshuaCrestone/RulesPythonImportIssues so that it reliably reproduces the issue. On my machine, cd'ing into the project directory and running:
```
bazel test //:dataflow_test --test_output=all
```

yields:
```
Traceback (most recent call last):
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1215, in _dot_lookup
    return getattr(thing, comp)
AttributeError: module 'googleapiclient' has no attribute 'discovery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1322, in patched
    with self.decoration_helper(patched,
  File "/home/joshua/miniconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1304, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/home/joshua/miniconda3/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1377, in __enter__
    self.target = self.getter()
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1552, in <lambda>
    getter = lambda: _importer(target)
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1228, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/joshua/miniconda3/lib/python3.8/unittest/mock.py", line 1217, in _dot_lookup
    __import__(import_path)
  File "/home/joshua/.cache/bazel/_bazel_joshua/122af99d1d1c19cf8294528207706890/sandbox/linux-sandbox/9/execroot/RulesPythonImportIssues/bazel-out/k8-fastbuild/bin/dataflow_test.runfiles/pip/pypi__google_api_python_client/googleapiclient/discovery.py", line 50, in <module>
    import google.api_core.client_options
ModuleNotFoundError: No module named 'google.api_core'
```

Unfortunately, https://github.com/thundergolfer-playground/rules_python-issue-431 gives me a 404.

**Comment by thundergolfer** [comment]
> gives me a 404.

Sorry was private. Now public.

**Comment by thundergolfer** [comment]
Thanks for the repro update. I've forked it and started it up in Github Codespaces and I don't get the same error still. I get:

```
======================================================================
ERROR: test_launch_template (__main__.DataflowMonitorTest)
DataflowMonitorTest.test_launch_template
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/home/codespace/.cache/bazel/_bazel_codespace/6169a4afe7d0cbdbab7fe9ff25ca97fd/sandbox/linux-sandbox/2/execroot/RulesPythonImportIssues/bazel-out/k8-fastbuild/bin/dataflow_test.runfiles/RulesPythonImportIssues/dataflow_test.py", line 31, in test_launch_template
    project_id = gcp_responses.PROJECT_ID
NameError: name 'gcp_responses' is not defined
```

Bazel version is the same (3.1.0) and platform is:

```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
```

**Comment by husafan** [comment]
I can confirm that this does not reproduce with the following steps:

1. `docker run -it --entrypoint=/bin/bash continuumio/miniconda3`
2. `apt update && apt install -y gcc`
3. `conda install -y bazel`
4. `git clone https://github.com/thundergolfer-forks/RulesPythonImportIssues.git`
5. `cd RulesPythonImportIssues/`
6. `bazel test //:dataflow_test --test_output=all`

```
======================================================================
ERROR: test_launch_template (__main__.DataflowMonitorTest)
DataflowMonitorTest.test_launch_template
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/root/.cache/bazel/_bazel_root/7e87604fdc563ea874ad7ab6f76018c0/sandbox/processwrapper-sandbox/1/execroot/RulesPythonImportIssues/bazel-out/k8-fastbuild/bin/dataflow_test.runfiles/RulesPythonImportIssues/dataflow_test.py", line 31, in test_launch_template
    project_id = gcp_responses.PROJECT_ID
NameError: name 'gcp_responses' is not defined
```

This must mean it is an issue with my local environment. I will try again with a clean conda install. Thank you for taking the time to look into this!

**Comment by husafan** [comment]
I reset my local conda environment which had:

```
  - google-auth=1.27.1=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.3=pyhd3eb1b0_0
  - google-pasta=0.2.0=py_0
```

This has fixed the issue for me. Please feel free to close this and thank you again for your responsiveness.

**Comment by thundergolfer** [comment]
Ahh so I think you hit a problem with the default non-hermetic python setup, if I understand "local conda env" correctly. We need a better start around onboarding users into a more hermetic toolchain that won't leak system deps into targets.

**Comment by caseyduquettesc** [comment]
@thundergolfer I'm getting this error consistently, but only on 0.3.0. When I switch to 0.2.0, the error goes away. I'm not sure where the regression is. I have a simple repro repo.

https://github.com/caseyduquettesc/rules_python_demo

```
% bazel run //scripts/demo
INFO: Invocation ID: 3dd0bf13-d654-44ff-b250-34e69abb2cd7
INFO: Analyzed target //scripts/demo:demo (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //scripts/demo:demo up-to-date:
  bazel-bin/scripts/demo/demo
INFO: Elapsed time: 0.217s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Running command line: bazel-bin/scripts/demo/demo
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/Users/.cache/_bazel_root/3e48c9752578ebae810f99b25573480c/execroot/demo/bazel-out/darwin-fastbuild/bin/scripts/demo/demo.runfiles/demo/scripts/demo/demo.py", line 1, in <module>
    from google.api_core.exceptions import ResourceExhausted
ModuleNotFoundError: No module named 'google.api_core'
```

**Comment by thundergolfer** [comment]
Thanks for the repro @caseyduquettesc. I have an idea where the regression could be.

**Comment by thundergolfer** [comment]
@caseyduquettesc I assumed you were using `pip_install` but you are actually using `pip_parse`. If I swap in `pip_install` then your demo repos can successfully run `bazel run //scripts/demo` with `0.3.0`. So this is a `pip_parse` bug.

If I switch to `0.2.0` in your repo, and comment out the `pip_compile_requirements` code, then it also succeeds with `pip_parse`. So there's been a regression in `pip_parse` between `0.2.0` and `0.3.0`. Can you please open an issue for this?
