### ISSUE TITLE
pip_install fails with: Invalid WHEEL file. Expected key 'Root-Is-Purelib'

### ISSUE THREAD

**Issue by amirh** [bazelbuild/rules_python#435]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip_install

### Is this a regression?

 No

### Description

pip_install fails installing platlib dependencies (e.g catboost)

## 🔬 Minimal Reproduction

I staged a repository that reproduces the issue here: https://github.com/amirh/bazel_platlib_repro
to reproduce in that repository run `bazel build repro:repro`

## 🔥 Exception or Error

<pre><code>
 (Traceback (most recent call last):
  File "/Users/amir/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/amir/.pyenv/versions/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_amir/85d4a1787a3dae9aaa9ef9ea1408d68e/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/private/var/tmp/_bazel_amir/85d4a1787a3dae9aaa9ef9ea1408d68e/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 104, in main
    for whl in glob.glob("*.whl")
  File "/private/var/tmp/_bazel_amir/85d4a1787a3dae9aaa9ef9ea1408d68e/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 104, in <listcomp>
    for whl in glob.glob("*.whl")
  File "/private/var/tmp/_bazel_amir/85d4a1787a3dae9aaa9ef9ea1408d68e/external/rules_python/python/pip_install/extract_wheels/lib/bazel.py", line 172, in extract_wheel
    purelib.spread_purelib_into_root(directory)
  File "/private/var/tmp/_bazel_amir/85d4a1787a3dae9aaa9ef9ea1408d68e/external/rules_python/python/pip_install/extract_wheels/lib/purelib.py", line 21, in spread_purelib_into_root
    % wheel_metadata_file_path
ValueError: Invalid WHEEL file 'pypi__catboost/catboost-0.24.4.dist-info/WHEEL'. Expected key 'Root-Is-Purelib'.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 11.2.3 
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Starting local Bazel server and connecting to it...
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
c37ba2215eccab53ae1da5f827a335281f81b9e1
  </code>
</pre>

**Anything else relevant?**

**Comment by thundergolfer** [comment]
Thanks for the issue report. 

I presume `catboost` is not populating this field, but I haven't yet checked.

The `pip_install` implementation does explicitly check for `Root-is-Purelib` and raises the exception you see when it's not found: https://github.com/bazelbuild/rules_python/blob/7aaf7627485c84c4ecd976f7b3fa940f60bb007c/python/pip_install/extract_wheels/lib/purelib.py#L20

Checking [the PEP for Wheels](https://www.python.org/dev/peps/pep-0491/#file-format) I cannot see it saying that the field _must_ be set and have a boolean value, so I think we can take the absence of the field to mean `false`.

**Comment by thundergolfer** [comment]
This has now been fixed in the `catboost` package (see ref below) and should hit the next release of that package, but will leave this open as add Root-is-Purelib to `catboost` does fix the issue for future packages.

**Ref:** https://github.com/catboost/catboost/pull/1695

**Comment by thundergolfer** [comment]
Closing as now fixed on `main`
