### ISSUE TITLE
CentOS 7 failure

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_python#45]
Version which works correctly
```
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "8f3daa17c1e5050cf0382f7fe60c1cd7c7067f3c",
)
```

Broken version (latest master)
```
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "3e167dcfb17356c68588715ed324c5e9b76f391d",
)
```

CentOS 7 and python 2.7 failure
```
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@requirements_xunitmerge//': pip_import failed:  (Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jenkins/.cache/bazel/_bazel_jenkins/cff2319697c0ff2c301458e924e0bef7/external/io_bazel_rules_python/tools/piptool.par/__main__.py", line 16, in <module>
  File "/home/jenkins/.cache/bazel/_bazel_jenkins/cff2319697c0ff2c301458e924e0bef7/external/io_bazel_rules_python/tools/piptool.par/subpar/runtime/support.py", line 228, in setup
  File "/home/jenkins/.cache/bazel/_bazel_jenkins/cff2319697c0ff2c301458e924e0bef7/external/io_bazel_rules_python/tools/piptool.par/subpar/runtime/support.py", line 209, in _setup_pkg_resources
TypeError: add() got an unexpected keyword argument 'replace'
)
INFO: Elapsed time: 4.130s
FAILED: Build did NOT complete successfully
```

WORKSPACE file
```
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "3e167dcfb17356c68588715ed324c5e9b76f391d",
)
load("@io_bazel_rules_python//python:pip.bzl", "pip_repositories", "pip_import")
pip_repositories()

pip_import(name = "requirements_xunitmerge", requirements = "//py:requirements.xunitmerge.txt")
load("@requirements_xunitmerge//:requirements.bzl", pip_install_xunitmerge="pip_install")
pip_install_xunitmerge()
```
py/requirements/xunitmerge.txt
```
xunitmerge
```

**Comment by mattmoor** [comment]
@duggelz This looks like an issue with the `google/subpar` hook.

**Comment by duggelz** [comment]
If you could determine what version of setuptools is installed, it would help debugging.  Something like `python2.7 -c 'import setuptools; print(setuptools.__version__)'`

**Comment by excavador** [comment]
```
[root@ci-slave-1:Ireland oleg]# python2.7 -c 'import setuptools; print(setuptools.__version__)'
0.9.8
```

**Comment by duggelz** [comment]
Current version is like 36.something, so 0.9.8 is going to be a problem. I
will add a version check, but the check will simply disable the
functionality.  Your workaround is to update the setuptools package, either
at the OS level or inside a virtualenv.

**Comment by excavador** [comment]
Thank you for explanation.
We definitely need some solution of #42
