### ISSUE TITLE
pip install example not working

### ISSUE THREAD

**Issue by XiaoConstantine** [bazelbuild/rules_python#541]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

OS: MacOS Big Sur(11.6) Intel Chip
Bazel Version: 3.7.0

I just cloned the latest master and try to run through `examples` directory.

```bash
bazel run :main
```

Output:

```bash
/Users/xiao/development/rules_python/examples/pip_install/build-support/bazel/bin/bazel-3.7.0 run :main
ERROR: Traceback (most recent call last):
	File "/Users/xiao/development/rules_python/examples/pip_install/BUILD", line 9, column 40, in <toplevel>
		load("@rules_python//python:pip.bzl", "compile_pip_requirements")
Error: file '@rules_python//python:pip.bzl' does not contain symbol 'compile_pip_requirements'
```

## 🔬 Minimal Reproduction
1. Get the repo
2. Go to `rules_python/examples/pip_install`
3. `bazel run :main`

## 🔥 Exception or Error

<pre><code>

/Users/xiao/development/rules_python/examples/pip_install/build-support/bazel/bin/bazel-3.7.0 run :main
ERROR: Traceback (most recent call last):
	File "/Users/xiao/development/rules_python/examples/pip_install/BUILD", line 9, column 40, in <toplevel>
		load("@rules_python//python:pip.bzl", "compile_pip_requirements")
Error: file '@rules_python//python:pip.bzl' does not contain symbol 'compile_pip_requirements'

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OS: MacOS Big Sur(11.6) Intel Chip
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
3.7.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
latest master
  </code>
</pre>

**Anything else relevant?**

**Comment by thundergolfer** [comment]
Sorry about this. Reasonably often people land changes in the examples/ which aren't compatible with the example's rules_python version. We should be better about following up on these breakages. 

Latest `main` commit works, so I've set the example up with that in #547.
