### ISSUE TITLE
pip_import broken on Windows

### ISSUE THREAD

**Issue by 4ZM** [bazelbuild/rules_python#57]
pip_import doesn't work on Windows (funcsigs is a dependency for unittest, so it's pretty much required for every project).
 
```
$ bazel.exe build ...
Loading:
Loading: 0 packages loaded
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@piptool_deps//': pip_import failed: Collecting pip==9.0.1 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 1))
  Using cached pip-9.0.1-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\pip-9.0.1-py2.py3-none-any.whl
Collecting setuptools==38.2.4 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 2))
  Using cached setuptools-38.2.4-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\setuptools-38.2.4-py2.py3-none-any.whl
Collecting wheel==0.30.0a0 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 3))
  Using cached wheel-0.30.0a0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\wheel-0.30.0a0-py2.py3-none-any.whl
Collecting mock==2.0.0 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached mock-2.0.0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\mock-2.0.0-py2.py3-none-any.whl
Collecting six>=1.9 (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached six-1.11.0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\six-1.11.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\pbr-3.1.1-py2.py3-none-any.whl
Skipping pip, due to already being wheel.
Skipping setuptools, due to already being wheel.
Skipping wheel, due to already being wheel.
Skipping mock, due to already being wheel.
Skipping six, due to already being wheel.
Skipping funcsigs, due to already being wheel.
Skipping pbr, due to already being wheel.
 (Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 232, in <module>
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 174, in main
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 155, in determine_possible_extras
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 155, in <dictcomp>
  File "C:\users\asum\windev\rules_python\tools\piptool.par\io_bazel_rules_python\rules_python\whl.py", line 102, in extras
  File "C:\users\asum\windev\rules_python\tools\piptool.par\io_bazel_rules_python\rules_python\whl.py", line 68, in metadata
  File "C:\Python27\lib\zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "C:\Python27\lib\zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'funcsigs-1.0.2.dist-info\\\\METADATA' in the archive"
)
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@piptool_deps//': pip_import failed: Collecting pip==9.0.1 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 1))
  Using cached pip-9.0.1-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\pip-9.0.1-py2.py3-none-any.whl
Collecting setuptools==38.2.4 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 2))
  Using cached setuptools-38.2.4-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\setuptools-38.2.4-py2.py3-none-any.whl
Collecting wheel==0.30.0a0 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 3))
  Using cached wheel-0.30.0a0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\wheel-0.30.0a0-py2.py3-none-any.whl
Collecting mock==2.0.0 (from -r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached mock-2.0.0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\mock-2.0.0-py2.py3-none-any.whl
Collecting six>=1.9 (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached six-1.11.0-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\six-1.11.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r C:/users/asum/windev/rules_python/python/requirements.txt (line 6))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
  Saved c:\users\asum\appdata\local\temp\_bazel_asum\uub-8znx\external\piptool_deps\pbr-3.1.1-py2.py3-none-any.whl
Skipping pip, due to already being wheel.
Skipping setuptools, due to already being wheel.
Skipping wheel, due to already being wheel.
Skipping mock, due to already being wheel.
Skipping six, due to already being wheel.
Skipping funcsigs, due to already being wheel.
Skipping pbr, due to already being wheel.
 (Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 232, in <module>
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 174, in main
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 155, in determine_possible_extras
  File "C:\users\asum\windev\rules_python\tools\piptool.par\__main__.py", line 155, in <dictcomp>
  File "C:\users\asum\windev\rules_python\tools\piptool.par\io_bazel_rules_python\rules_python\whl.py", line 102, in extras
  File "C:\users\asum\windev\rules_python\tools\piptool.par\io_bazel_rules_python\rules_python\whl.py", line 68, in metadata
  File "C:\Python27\lib\zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "C:\Python27\lib\zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'funcsigs-1.0.2.dist-info\\\\METADATA' in the archive"
)
INFO: Elapsed time: 8,251s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by 4ZM** [comment]
Can confirm this is fixed on head of master.
