### ISSUE TITLE
pip_parse blows up when #egg is not specified

### ISSUE THREAD

**Issue by robbrit** [bazelbuild/rules_python#576]
Bazel version:
```
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
```
Rules Python version:
```
http_archive(
    name = "rules_python",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
)
```

When I forgot to put the `#egg` parameter for the URL of a Github package, bazel will crash when it attempts to process the `requirements.lock.txt` file.

To reproduce:

1. Specify a requirement by URL in the `requirements.in` file without the `#pip` parameter passed:
    ```
    # in requirements.in
    https://github.com/noahmorrison/chevron/archive/5e1c12827b7fc3db30cb3b24cae9a7ee3092822b.zip
   ```
1. Run the corresponding `compile_pip_requrements` rule:
    ```
    bazel run //third_party/python:requirements.update
    ```
1. Run it again (or attempt to build/run any target that uses these requirements):
    ```
    bazel run //third_party/python:requirements.update
    ```

The second run of the `compile_pip_requirements` rule blows up:
```
no such package '@py_deps//': rules_python failed:  (Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/parse_requirements_to_bzl/__main__.py", line 5, in <module>
    main()
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/parse_requirements_to_bzl/__init__.py", line 167, in main
    generate_parsed_requirements_contents(args)
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/parse_requirements_to_bzl/__init__.py", line 66, in generate_parsed_requirements_contents
    repo_names_and_reqs = repo_names_and_requirements(install_req_and_lines, repo_prefix)
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/parse_requirements_to_bzl/__init__.py", line 40, in repo_names_and_requirements
    return [
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/parse_requirements_to_bzl/__init__.py", line 42, in <listcomp>
    bazel.sanitise_name(ir.name, prefix=repo_prefix),
  File "/home/rob/.cache/bazel/_bazel_rob/3eb8858519416b15427b22c14abb9232/external/rules_python/python/pip_install/extract_wheels/lib/bazel.py", line 241, in sanitise_name
    return prefix + name.replace("-", "_").replace(".", "_").lower()
AttributeError: 'NoneType' object has no attribute 'replace'
)
```

My workaround for now:
1. Delete the entry from `requirements.lock.txt`.
2. Update `requirements.in` to add `#egg=chevron` to the URL.
3. Rerun `compile_pip_requirements`.

The workaround is easy so it's not the end of the world, just putting this in here in case someone runs into it and loses some of their sanity trying to figure out what they forgot.

**Comment by hrfuller** [comment]
Hi @robbrit thanks for the report. This seems like an issue with pip_tools not knowing the name of a package that it places in requirements.lock.txt. We defer to pip here to parse the names from the list of requirements so I'm not sure this is a bug with rules_python exactly, though it looks like we could handle the error more gracefully and potentially give a useful recommendation to the user.

**Comment by robbrit** [comment]
Yeah this is not too hard to work around, it's just when someone is coming from a non-bazel setup it's possible for the `requirements.in` file that works just fine with pip to not work with bazel. A clearer error message would be helpful to save some time.
