### ISSUE TITLE
Errors gathering hermetic python about zstd

### ISSUE THREAD

**Issue by RyanDraves** [bazelbuild/rules_python#683]
# 🐞 bug report

### Affected Rule

The issue is caused by `python_register_toolchains`, rule `python3_8_x86_64-unknown-linux-gnu` in particular.

### Is this a regression?

First version I'm using.

### Description

Using a hermetic Python installation does not declare `zstd` as a dependency. This produces some warning messages, but the fetch process can fail if `zstd` is not otherwise installed.

## 🔬 Minimal Reproduction

In a `WORKSPACE` file:
```
http_archive(
    name = "rules_python",
    strip_prefix = "rules_python-0.8.0",
    url =
    "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.8.0.tar.gz",
    sha256 = "9fcf91dbcc31fde6d1edb15f117246d912c33c36f44cf681976bd886538deba6",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_8",
    # Available versions are listed in @rules_python//python:versions.bzl.
    python_version = "3.8.10",
)

load("@python3_8//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
    name = "my_deps",
    requirements = "//:requirements.txt",
    python_interpreter_target = interpreter,
)
```

## 🔥 Exception or Error

During builds, the following warning will often appear:
```
DEBUG: Rule 'python3_8_x86_64-unknown-linux-gnu' indicated that a canonical reproducible form can be obtained by modifying arguments url = "https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz"
DEBUG: Repository python3_8_x86_64-unknown-linux-gnu instantiated at:
  $HOME/repo/WORKSPACE:33:27: in <toplevel>
  /path/to/cache/external/rules_python/python/repositories.bzl:254:26: in python_register_toolchains
Repository rule python_repository defined at:
  /path/to/cache/external/rules_python/python/repositories.bzl:164:36: in <toplevel>
```
When running on a machine without `zstd` externally installed, the following error can appear:
```
INFO: Repository python3_8_x86_64-unknown-linux-gnu instantiated at:
  $HOME/repo/WORKSPACE:33:27: in <toplevel>
  /path/to/cache/external/rules_python/python/repositories.bzl:254:26: in python_register_toolchains
Repository rule python_repository defined at:
  /path/to/cache/external/rules_python/python/repositories.bzl:164:36: in <toplevel>
INFO: Repository 'python3_8_x86_64-unknown-linux-gnu' used the following cache hits instead of downloading the corresponding file.
 * Hash '7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0' for https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz
 * Hash 'aec8c4c53373b90be7e2131093caa26063be6d9d826f599c935c0e1042af3355' for https://github.com/indygreg/python-build-standalone/releases/download/20210506/cpython-3.8.10-x86_64-unknown-linux-gnu-pgo+lto-20210506T0943.tar.zst
If the definition of 'python3_8_x86_64-unknown-linux-gnu' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'python3_8_x86_64-unknown-linux-gnu':
   Traceback (most recent call last):
	File "/path/to/cache/external/rules_python/python/repositories.bzl", line 79, column 17, in _python_repository_impl
		fail(exec_result.stderr)
Error in fail: tar (child): ./unzstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/path/to/cache/rules_python/python/repositories.bzl", line 79, column 17, in _python_repository_impl
		fail(exec_result.stderr)
Error in fail: tar (child): ./unzstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: $HOME/repo/BUILD:13:10: //:my_target depends on @python3_8_x86_64-unknown-linux-gnu//:python_runtimes in repository @python3_8_x86_64-unknown-linux-gnu which failed to fetch. no such package '@python3_8_x86_64-unknown-linux-gnu//': tar (child): ./unzstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**Output of `bazel version`:**

```
Bazelisk version: v1.0
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
Extracting Bazel installation...
Build label: 5.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 24 14:02:30 2022 (1648130550)
Build timestamp: 1648130550
Build timestamp as int: 1648130550
```

**Rules_python version:**

0.8.0

**Anything else relevant?**

**Comment by thundergolfer** [comment]
Thanks for your detailed issue report.

I believe what happened here if that the host did not provide `zstd` (normal) and thus the rules_python code fell back to building the tool. The compilation of `zstd` failed, and thus the tool wasn't created at the expected location.

> `Error in fail: tar (child): ./unzstd: Cannot exec: No such file or directory`

But this failure was not picked up by Bazel because the return code of the process was not checked. 

That missing error check was fixed in https://github.com/bazelbuild/rules_python/commit/bd1a78de9faee19e3a91d3fa3bae2be9e33b1955 (most recent `main` commit, landed 5 days ago) so I think this issue is now resolved.

I believe if you use [3.8.12](https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl#L39) (just a patch version upgrade) then you'll no longer take a dependency on zstd, and thus won't need to built it if it's not present on the host.
