### ISSUE TITLE
ARM64 Darwin Toolchain Issues

### ISSUE THREAD

**Issue by jarreds** [bazelbuild/rules_python#725]
# 🐞 bug report

### Description

I'm attempting to register a Python toolchain on a new ARM64 Darwin machine with the following:

```python
http_archive(
    name = "rules_python",
    sha256 = "cdf6b84084aad8f10bf20b46b77cb48d83c319ebe6458a18e9d2cebf57807cdd",
    strip_prefix = "rules_python-0.8.1",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.8.1.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python39",
    python_version = "3.9.10",
)

load("@python39//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements.txt",
)

load("@pip//:requirements.bzl", "install_deps")

install_deps()
```

## 🔥 Exception or Error

Running the above setup in `WORKSPACE` on this architecture results in:

```
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Repository python39_aarch64-apple-darwin instantiated at:
  /Users/user/src/github.com/acme/core/WORKSPACE:77:27: in <toplevel>
  /private/var/tmp/_bazel_user/63162deb35ba6b2f678241a64a1d59bb/external/rules_python/python/repositories.bzl:272:26: in python_register_toolchains
Repository rule python_repository defined at:
  /private/var/tmp/_bazel_user/63162deb35ba6b2f678241a64a1d59bb/external/rules_python/python/repositories.bzl:180:36: in <toplevel>
INFO: Repository 'python39_aarch64-apple-darwin' used the following cache hits instead of downloading the corresponding file.
 * Hash 'ad66c2a3e7263147e046a32694de7b897a46fb0124409d29d3a93ede631c8aee' for https://github.com/indygreg/python-build-standalone/releases/download/20220227/cpython-3.9.10+20220227-aarch64-apple-darwin-install_only.tar.gz
If the definition of 'python39_aarch64-apple-darwin' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'python39_aarch64-apple-darwin':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/63162deb35ba6b2f678241a64a1d59bb/external/rules_python/python/repositories.bzl", line 102, column 17, in _python_repository_impl
		fail(exec_result.stderr)
Error in fail: 
ERROR: WORKSPACE:77:27: fetching python_repository rule //external:python39_aarch64-apple-darwin: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/63162deb35ba6b2f678241a64a1d59bb/external/rules_python/python/repositories.bzl", line 102, column 17, in _python_repository_impl
		fail(exec_result.stderr)
Error in fail: 
ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip//': no such package '@python39_aarch64-apple-darwin//': 
INFO: Elapsed time: 1.436s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

## 🌍  Your Environment

<img width="207" alt="image" src="https://user-images.githubusercontent.com/1414175/172706383-37b07461-a67a-43dc-ae8f-d4ab7d889063.png">

**Output of `bazel version`:**

```
Bazelisk version: development
Build label: 5.2.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:09 2022 (1654618269)
Build timestamp: 1654618269
Build timestamp as int: 1654618269
```

**Comment by thundergolfer** [comment]
Hmm, I copied your `WORKSPACE.bazel`, created an empty `BUILD.bazel` in the root and an empty `requirements.txt` file and got a working build.

```
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 1.353s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

My system is basically the same as yours.

**About this Mac**

```
macOS Monterey
Version 12.2.1

Macbook Pro (16-inch, 2021)
Chip Apple M1 Max
Memory 64 GB
```

**uname -a**

```
Darwin 192-168-1-111.tpgi.com.au 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
```

**bazel version**

```
Bazelisk version: v1.5.0
Build label: 5.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:03 2022 (1654618263)
Build timestamp: 1654618263
Build timestamp as int: 1654618263
```

**Comment by thundergolfer** [comment]
What's suspicious from the logs is this:

```
Error in fail: 
ERROR: WORKSPACE:77:27: fetching python_repository rule //external:python39_aarch64-apple-darwin: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/63162deb35ba6b2f678241a64a1d59bb/external/rules_python/python/repositories.bzl", line 102, column 17, in _python_repository_impl
		fail(exec_result.stderr)
```

That `Error in fail:` line is an empty failure message. 

At release `0.8.1` that code is https://github.com/bazelbuild/rules_python/blob/0.8.1/python/repositories.bzl#L102

That `chmod` should be returning a failure message.

**Comment by jarreds** [comment]
For me, looks like it's the same exact same issue outlined here https://github.com/bazelbuild/rules_python/issues/662#issuecomment-1091840944

If I change the executable to `/bin/chmod` within https://github.com/bazelbuild/rules_python/blob/0.8.1/python/repositories.bzl#L102:

```
        exec_result = rctx.execute(["/bin/chmod", "-R", "ugo-w", "lib"])
```

Everything works as expected.

**Comment by jarreds** [comment]
Upgrading to the latest coreutils via Homebrew resolved the issue. I believe this was the underlying bug https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50784

**Comment by thundergolfer** [comment]
Thanks for the extra detail. At the least we can augment the error message to make the `Error in fail` line more detailed and not just rely on `chmod`'s output (which here was no output).
