### ISSUE TITLE
Error calling pip_parse in latest release

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/rules_python#746]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `pip_parse`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.9.0

### Description

Upgrading to rules_python 0.10.0 with our own py_toolchain causes `pip_parse` to fail when you provide a `python_interpreter_target` that wasn't generated by rules_python because `STANDALONE_INTERPRETER_FILENAME` doesn't exist and the code seems to assume it does.

## 🔥 Exception or Error

<pre><code>
ERROR: An error occurred during the fetch of repository 'py_deps':
   Traceback (most recent call last):
        File "/Users/casey.duquette/Snapchat/Dev/.cache/_bazel_root/b201cbe3bc260ed3896346109ccb8a9c/external/rules_python/python/pip_install/pip_repository.bzl", line 228, column 63, in _pip_repository_impl
                environment = _create_repository_execution_environment(rctx),
        File "/Users/casey.duquette/Snapchat/Dev/.cache/_bazel_root/b201cbe3bc260ed3896346109ccb8a9c/external/rules_python/python/pip_install/pip_repository.bzl", line 151, column 37, in _create_repository_execution_environment
                _maybe_set_xcode_location_cflags(rctx, env)
        File "/Users/casey.duquette/Snapchat/Dev/.cache/_bazel_root/b201cbe3bc260ed3896346109ccb8a9c/external/rules_python/python/pip_install/pip_repository.bzl", line 79, column 18, in _maybe_set_xcode_location_cflags
                rctx.path(Label("@{}//:{}".format(rctx.attr.python_interpreter_target.workspace_name, STANDALONE_INTERPRETER_FILENAME))) and
Error in path: Not a regular file: /Users/casey.duquette/Snapchat/Dev/.cache/_bazel_root/b201cbe3bc260ed3896346109ccb8a9c/external/snap_tool_py_3_10/STANDALONE_INTERPRETER
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 12.4
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed May 4 17:45:51 2022 (1651686351)
Build timestamp: 1651686351
Build timestamp as int: 1651686351
  </code>
</pre>

(internal fork)

**Rules_python version:**

<pre>
  <code>
0.10.0
  </code>
</pre>

**Anything else relevant?**

**Comment by groodt** [comment]
I think this might have been introduced here:
https://github.com/bazelbuild/rules_python/commit/ab6940a96ce0eeed10870b51fb02b5d13da61531#diff-bced444149cf9f25b36837efb2792070f362650b01f553d9d01bef080ebfefabR69-R91

cc @hrfuller

**Comment by hrfuller** [comment]
Thanks for opening. I'll take a look at resolving this.
