### ISSUE TITLE
Cant install owlready2

### ISSUE THREAD

**Issue by KukumavMozolo** [bazelbuild/rules_python#786]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
whl_library

### Description

When I try to run a target that has owlready2 as a requirement in its deps. The process fails with the following error message:
ERROR: No matching distribution found for owlready2==0.38
I can install all other dependencies. When using pip-sync directly it works.

## 🔬 Minimal Reproduction

Try building a the target with the following lock file(created with compile_pip_requirements):

```
py_binary(
    name = "test",
    srcs = ["test.py"],
    deps = [
        requirement("owlready2"),
    ],
)
```

```
#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    bazel run //field33_ml:requirements.update
#
owlready2==0.38 \
    --hash=sha256:0d13841fc9d2f1091b07fd0f85848830286e60653d4b64b92e44e13024b3ebfc
    # via -r field33_ml/requirements.in

```

```
workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6",
    strip_prefix = "rules_python-0.10.2",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@python39//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pypi",
    extra_pip_args = [
        "--no-cache-dir",
        "--only-binary",
        ":all:",
    ],
    isolated = True,
    python_interpreter_target = interpreter,
    requirements_lock = "//test:requirements_lock.txt",
)

load("@pypi//:requirements.bzl", "install_deps")

# Initialize repositories for all packages in requirements_lock.txt.
install_deps()

```

## 🔥 Exception or Error

```
 depends on @pypi_owlready2//:pkg in repository @pypi_owlready2 which failed to fetch. no such package '@pypi_owlready2//': whl_library pypi_owlready2 failed:  (ERROR: Could not find a version that satisfies the requirement owlready2==0.38 (from versions: none)
ERROR: No matching distribution found for owlready2==0.38
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/python39_x86_64-unknown-linux-gnu/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/python39_x86_64-unknown-linux-gnu/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 81, in <module>
    main()
  File "/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 57, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/python39_x86_64-unknown-linux-gnu/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/user/.cache/bazel/_bazel_user/77aeb91b86f4c1e544eeef10e617add4/external/python39_x86_64-unknown-linux-gnu/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--no-cache-dir', '--only-binary', ':all:', '-r', '/tmp/tmpsqwn_kc2']' returned non-zero exit status 1.
)
```

## 🌍  Your Environment

**Operating System:**
<pre>
  <code>
Ubuntu 20.04.3
  </code>
</pre>

**Output of `bazel version`:**
<pre>
  <code>
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_python version:**
<pre>
  <code>
rules_python-0.10.2
  </code>
</pre>
**Anything else relevant?**

**Comment by mattem** [comment]
Do you have the `--only-binary=:all:` flag set on your `pip_parse` or `pip_install` rule? (The minimal repro is a little too minimal). If so, then there is no wheel distribution for `owlready2` (https://pypi.org/project/Owlready2/#files), hence the error from pip.

**Comment by KukumavMozolo** [comment]
Omg thanks a lott: adding
`        "--no-binary",
        "owlready2",`
to pip_parse solved it!
