### ISSUE TITLE
Regressions of rules_python functionality identified by Bazel CI (affecting Protobuf)

### ISSUE THREAD

**Issue by perezd** [bazelbuild/rules_python#818]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip_install (presumably)

### Is this a regression?

Yes

 Yes, the previous version in which this bug was not present was: 
https://github.com/protocolbuffers/upb/commit/4135cd206b92b19a438b63a87bb35a7c30cc5913

### Description

 A clear and concise description of the problem...

We were notified by Bazel CI that our project is failing after we recently updated to rules_python 0.11.0:
https://github.com/protocolbuffers/upb/issues/760

## 🔬 Minimal Reproduction

Break link:
https://buildkite.com/bazel/upb/builds/1235#0182f140-e79a-40af-80c7-844e49d722ad

## 🔥 Exception or Error

<pre><code>

agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
(00:16:08) ERROR: /workdir/upb/fuzz/BUILD:5:13: //upb/fuzz:file_descriptor_parsenew_fuzzer_corpus depends on @rules_fuzzing//fuzzing/tools:make_corpus_dir in repository @rules_fuzzing which failed to fetch. no such package '@fuzzing_py_deps//': rules_python failed:  (Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_python/python/pip_install/extract_wheels/extract_wheels.py", line 15, in <module>
    from python.pip_install.extract_wheels import (
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_python/python/pip_install/extract_wheels/bazel.py", line 9, in <module>
    from python.pip_install.extract_wheels import annotation, namespace_pkgs, wheel
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_python/python/pip_install/extract_wheels/wheel.py", line 5, in <module>
    import installer
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/pypi__installer/installer/__init__.py", line 6, in <module>
    from installer._core import install  # noqa
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/pypi__installer/installer/_core.py", line 7, in <module>
    from installer.destinations import WheelDestination
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/pypi__installer/installer/destinations.py", line 19, in <module>
    from installer.scripts import Script
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/pypi__installer/installer/scripts.py", line 6, in <module>
    from importlib.resources import read_binary
ModuleNotFoundError: No module named 'importlib.resources'
)
(00:16:08) ERROR: Analysis of target '//upb/fuzz:file_descriptor_parsenew_fuzzer' failed; build aborted:
(00:16:08) INFO: Elapsed time: 1.929s
(00:16:08) INFO: 0 processes.
(00:16:08) ERROR: Couldn't start the build. Unable to run tests
(00:16:08) INFO: Build Event Protocol files produced successfully.
(00:16:08) FAILED: Build did NOT complete successfully (84 packages loaded, 1895 targets configured)
    currently loading: @rules_fuzzing//fuzzing/tools
    Fetching @com_google_absl; fetching
    Fetching https://mirror.bazel.build/bazel_java_tools/releases/java/v11.7.1/java_tools-v11.7.1.zip; 11,902,896B
    Fetching https://mirror.bazel.build/openjdk/azul-zulu11.50.19-ca-jdk11.0.12/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz; 14,163,872B
    Fetching ...e_absl; Extracting /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com\
_google_absl/temp17839904549821454134/b9b925341f9e90f5e7aa0cf23f036c29c7e454eb.zip
    Fetching @zlib; fetching
    Fetching ...l/zlib; Extracting /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/zli\
b/temp949795591394095872/v1.2.11.tar.gz
bazel test failed with exit code 1
🚨 Error: The command exited with status 1
user command error: The plugin docker command hook exited with status 1
Running plugin docker pre-exit hook

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   Ubuntu 18.04 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
5.3.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.11.0
  </code>
</pre>

**Anything else relevant?**

The test image uses Python 3.6.9.

**Comment by Wyverald** [comment]
Thanks for confirming, @groodt! We'll look into upgrading the Python in our test image.
