### ISSUE TITLE
Fatal Python error: init_import_site: Failed to import the site module

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/rules_python#903]
# 🐞 bug report

When attempting to use the IntelliJ debugger to debug a test, the following error occurs:

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 610, in main
    execsitecustomize()
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 549, in execsitecustomize
    import sitecustomize
  File "/opt/intellij-ue-2021.3/plugins/python/helpers/pycharm_matplotlib_backend/sitecustomize.py", line 3, in <module>
    import traceback
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/traceback.py", line 3, in <module>
    import collections
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/collections/__init__.py", line 36, in <module>
    from operator import eq as _eq
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1544, in find_spec
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
KeyboardInterrupt
```

### Repro

```python
# WORKSPACE

################################################################################
## Python: Toolchain Setup
################################################################################

# Toolchain registration for reproducibility
# https://github.com/bazelbuild/rules_python#toolchain-registration
load("@rules_python//python:repositories.bzl", "python_register_toolchains")

# Available versions listed in https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl
python_register_toolchains(
    name = "python3_10",
    python_version = "3.10.6",
)

load("@python3_10//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

################################################################################
## Python: Dependencies
################################################################################

pip_parse(
    name = "py_deps",
    python_interpreter_target = interpreter,
    requirements_lock = "requirements_lock.txt",
)

load("@py_deps//:requirements.bzl", "install_deps")

install_deps()
```

```bash
# requirements_lock.txt
contourpy==1.0.6
cycler==0.11.0
fonttools==4.38.0
kiwisolver==1.4.4
matplotlib==3.6.2
numpy==1.23.5
packaging==21.3
pandas==1.5.2
pillow==9.3.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
six==1.16.0
```

```python
load("@rules_python//python:defs.bzl", "py_library")
load("@py_deps//:requirements.bzl", "requirement")

py_library(
    name = "foo",
    srcs = ["foo.py"],
    deps = [
        requirement("numpy"),
        requirement("pandas"),
        requirement("matplotlib"),
    ],
)

py_test(
    name = "foo_test",
    srcs = ["foo_test.py"],
    deps = [
        ":foo",
    ],
)
```

### Is this a regression?

I don't know

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 % uname -a
Linux redacted 5.19.11-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
 % bazel version        
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.14.0
  </code>
</pre>

**Anything else relevant?**

I have tried IntelliJ's Python SDK, the system python SDK, and the python SDK managed by bazel. The above error is using the python SDK managed by bazel. 

IntelliJ is version `IntelliJ IDEA 2021.3.3 (Ultimate Edition)`

IntelliJ bazel plugin version is `2022.06.28.0.0-api-version-213` (up to date at time of report)

**Comment by aryeh-looker** [comment]
I should note that although the error culprit is always `Fatal Python error: init_import_site: Failed to import the site module`, the backtrace is not consistent; e.g.:

```
/usr/bin/setsid --wait /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/execroot/tapestry/bazel-out/k8-fastbuild/bin/src/main/java/energy/tapestry/partner/cen/plp/results/operational_costs/main.runfiles/python3_10_x86_64-unknown-linux-gnu/bin/python3 /opt/intellij-ue-2021.3/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 42143 --file /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/execroot/tapestry/bazel-out/k8-fastbuild/bin/src/test/java/energy/tapestry/partner/cen/plp/results/operational_costs_test
Connected to pydev debugger (build 213.7172.25)
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 604, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 387, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt

Process finished with exit code 1
```

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 610, in main
    execsitecustomize()
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 549, in execsitecustomize
    import sitecustomize
  File "/opt/intellij-ue-2021.3/plugins/python/helpers/pycharm_matplotlib_backend/sitecustomize.py", line 3, in <module>
    import traceback
KeyboardInterrupt
```

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/site.py", line 73, in <module>
    import os
  File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/python3_10_x86_64-unknown-linux-gnu/lib/python3.10/os.py", line 29, in <module>
    from _collections_abc import _check_methods
KeyboardInterrupt
```
